// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

public interface LongRunningRecognizeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech_to_text.LongRunningRecognizeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .speech_to_text.SpeechRecognitionResult results = 1;</code>
   */
  java.util.List<ai.vernacular.speech.SpeechRecognitionResult> 
      getResultsList();
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionResult results = 1;</code>
   */
  ai.vernacular.speech.SpeechRecognitionResult getResults(int index);
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionResult results = 1;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionResult results = 1;</code>
   */
  java.util.List<? extends ai.vernacular.speech.SpeechRecognitionResultOrBuilder> 
      getResultsOrBuilderList();
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionResult results = 1;</code>
   */
  ai.vernacular.speech.SpeechRecognitionResultOrBuilder getResultsOrBuilder(
      int index);
}
