// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

/**
 * <pre>
 * Provides information to the recognizer that specifies how to process the request
 * </pre>
 *
 * Protobuf type {@code speech_to_text.RecognitionConfig}
 */
public  final class RecognitionConfig extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:speech_to_text.RecognitionConfig)
    RecognitionConfigOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RecognitionConfig.newBuilder() to construct.
  private RecognitionConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RecognitionConfig() {
    encoding_ = 0;
    languageCode_ = "";
    speechContexts_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RecognitionConfig();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RecognitionConfig(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            encoding_ = rawValue;
            break;
          }
          case 16: {

            sampleRateHertz_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            languageCode_ = s;
            break;
          }
          case 32: {

            maxAlternatives_ = input.readInt32();
            break;
          }
          case 42: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              speechContexts_ = new java.util.ArrayList<ai.vernacular.speech.SpeechContext>();
              mutable_bitField0_ |= 0x00000001;
            }
            speechContexts_.add(
                input.readMessage(ai.vernacular.speech.SpeechContext.parser(), extensionRegistry));
            break;
          }
          case 48: {

            audioChannelCount_ = input.readInt32();
            break;
          }
          case 56: {

            enableSeparateRecognitionPerChannel_ = input.readBool();
            break;
          }
          case 64: {

            enableWordTimeOffsets_ = input.readBool();
            break;
          }
          case 88: {

            enableAutomaticPunctuation_ = input.readBool();
            break;
          }
          case 130: {
            ai.vernacular.speech.SpeakerDiarizationConfig.Builder subBuilder = null;
            if (diarizationConfig_ != null) {
              subBuilder = diarizationConfig_.toBuilder();
            }
            diarizationConfig_ = input.readMessage(ai.vernacular.speech.SpeakerDiarizationConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(diarizationConfig_);
              diarizationConfig_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        speechContexts_ = java.util.Collections.unmodifiableList(speechContexts_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_RecognitionConfig_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_RecognitionConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.vernacular.speech.RecognitionConfig.class, ai.vernacular.speech.RecognitionConfig.Builder.class);
  }

  /**
   * Protobuf enum {@code speech_to_text.RecognitionConfig.AudioEncoding}
   */
  public enum AudioEncoding
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ENCODING_UNSPECIFIED = 0;</code>
     */
    ENCODING_UNSPECIFIED(0),
    /**
     * <code>LINEAR16 = 1;</code>
     */
    LINEAR16(1),
    /**
     * <code>FLAC = 2;</code>
     */
    FLAC(2),
    /**
     * <code>MP3 = 3;</code>
     */
    MP3(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ENCODING_UNSPECIFIED = 0;</code>
     */
    public static final int ENCODING_UNSPECIFIED_VALUE = 0;
    /**
     * <code>LINEAR16 = 1;</code>
     */
    public static final int LINEAR16_VALUE = 1;
    /**
     * <code>FLAC = 2;</code>
     */
    public static final int FLAC_VALUE = 2;
    /**
     * <code>MP3 = 3;</code>
     */
    public static final int MP3_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static AudioEncoding valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static AudioEncoding forNumber(int value) {
      switch (value) {
        case 0: return ENCODING_UNSPECIFIED;
        case 1: return LINEAR16;
        case 2: return FLAC;
        case 3: return MP3;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AudioEncoding>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AudioEncoding> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AudioEncoding>() {
            public AudioEncoding findValueByNumber(int number) {
              return AudioEncoding.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ai.vernacular.speech.RecognitionConfig.getDescriptor().getEnumTypes().get(0);
    }

    private static final AudioEncoding[] VALUES = values();

    public static AudioEncoding valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private AudioEncoding(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:speech_to_text.RecognitionConfig.AudioEncoding)
  }

  public static final int ENCODING_FIELD_NUMBER = 1;
  private int encoding_;
  /**
   * <code>.speech_to_text.RecognitionConfig.AudioEncoding encoding = 1;</code>
   * @return The enum numeric value on the wire for encoding.
   */
  public int getEncodingValue() {
    return encoding_;
  }
  /**
   * <code>.speech_to_text.RecognitionConfig.AudioEncoding encoding = 1;</code>
   * @return The encoding.
   */
  public ai.vernacular.speech.RecognitionConfig.AudioEncoding getEncoding() {
    @SuppressWarnings("deprecation")
    ai.vernacular.speech.RecognitionConfig.AudioEncoding result = ai.vernacular.speech.RecognitionConfig.AudioEncoding.valueOf(encoding_);
    return result == null ? ai.vernacular.speech.RecognitionConfig.AudioEncoding.UNRECOGNIZED : result;
  }

  public static final int SAMPLE_RATE_HERTZ_FIELD_NUMBER = 2;
  private int sampleRateHertz_;
  /**
   * <pre>
   * Valid values are: 8000-48000.
   * </pre>
   *
   * <code>int32 sample_rate_hertz = 2;</code>
   * @return The sampleRateHertz.
   */
  public int getSampleRateHertz() {
    return sampleRateHertz_;
  }

  public static final int LANGUAGE_CODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object languageCode_;
  /**
   * <code>string language_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The languageCode.
   */
  public java.lang.String getLanguageCode() {
    java.lang.Object ref = languageCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      languageCode_ = s;
      return s;
    }
  }
  /**
   * <code>string language_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for languageCode.
   */
  public com.google.protobuf.ByteString
      getLanguageCodeBytes() {
    java.lang.Object ref = languageCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      languageCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MAX_ALTERNATIVES_FIELD_NUMBER = 4;
  private int maxAlternatives_;
  /**
   * <code>int32 max_alternatives = 4;</code>
   * @return The maxAlternatives.
   */
  public int getMaxAlternatives() {
    return maxAlternatives_;
  }

  public static final int SPEECH_CONTEXTS_FIELD_NUMBER = 5;
  private java.util.List<ai.vernacular.speech.SpeechContext> speechContexts_;
  /**
   * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
   */
  public java.util.List<ai.vernacular.speech.SpeechContext> getSpeechContextsList() {
    return speechContexts_;
  }
  /**
   * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
   */
  public java.util.List<? extends ai.vernacular.speech.SpeechContextOrBuilder> 
      getSpeechContextsOrBuilderList() {
    return speechContexts_;
  }
  /**
   * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
   */
  public int getSpeechContextsCount() {
    return speechContexts_.size();
  }
  /**
   * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
   */
  public ai.vernacular.speech.SpeechContext getSpeechContexts(int index) {
    return speechContexts_.get(index);
  }
  /**
   * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
   */
  public ai.vernacular.speech.SpeechContextOrBuilder getSpeechContextsOrBuilder(
      int index) {
    return speechContexts_.get(index);
  }

  public static final int AUDIO_CHANNEL_COUNT_FIELD_NUMBER = 6;
  private int audioChannelCount_;
  /**
   * <code>int32 audio_channel_count = 6;</code>
   * @return The audioChannelCount.
   */
  public int getAudioChannelCount() {
    return audioChannelCount_;
  }

  public static final int ENABLE_SEPARATE_RECOGNITION_PER_CHANNEL_FIELD_NUMBER = 7;
  private boolean enableSeparateRecognitionPerChannel_;
  /**
   * <code>bool enable_separate_recognition_per_channel = 7;</code>
   * @return The enableSeparateRecognitionPerChannel.
   */
  public boolean getEnableSeparateRecognitionPerChannel() {
    return enableSeparateRecognitionPerChannel_;
  }

  public static final int ENABLE_WORD_TIME_OFFSETS_FIELD_NUMBER = 8;
  private boolean enableWordTimeOffsets_;
  /**
   * <code>bool enable_word_time_offsets = 8;</code>
   * @return The enableWordTimeOffsets.
   */
  public boolean getEnableWordTimeOffsets() {
    return enableWordTimeOffsets_;
  }

  public static final int ENABLE_AUTOMATIC_PUNCTUATION_FIELD_NUMBER = 11;
  private boolean enableAutomaticPunctuation_;
  /**
   * <code>bool enable_automatic_punctuation = 11;</code>
   * @return The enableAutomaticPunctuation.
   */
  public boolean getEnableAutomaticPunctuation() {
    return enableAutomaticPunctuation_;
  }

  public static final int DIARIZATION_CONFIG_FIELD_NUMBER = 16;
  private ai.vernacular.speech.SpeakerDiarizationConfig diarizationConfig_;
  /**
   * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
   * @return Whether the diarizationConfig field is set.
   */
  public boolean hasDiarizationConfig() {
    return diarizationConfig_ != null;
  }
  /**
   * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
   * @return The diarizationConfig.
   */
  public ai.vernacular.speech.SpeakerDiarizationConfig getDiarizationConfig() {
    return diarizationConfig_ == null ? ai.vernacular.speech.SpeakerDiarizationConfig.getDefaultInstance() : diarizationConfig_;
  }
  /**
   * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
   */
  public ai.vernacular.speech.SpeakerDiarizationConfigOrBuilder getDiarizationConfigOrBuilder() {
    return getDiarizationConfig();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (encoding_ != ai.vernacular.speech.RecognitionConfig.AudioEncoding.ENCODING_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, encoding_);
    }
    if (sampleRateHertz_ != 0) {
      output.writeInt32(2, sampleRateHertz_);
    }
    if (!getLanguageCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, languageCode_);
    }
    if (maxAlternatives_ != 0) {
      output.writeInt32(4, maxAlternatives_);
    }
    for (int i = 0; i < speechContexts_.size(); i++) {
      output.writeMessage(5, speechContexts_.get(i));
    }
    if (audioChannelCount_ != 0) {
      output.writeInt32(6, audioChannelCount_);
    }
    if (enableSeparateRecognitionPerChannel_ != false) {
      output.writeBool(7, enableSeparateRecognitionPerChannel_);
    }
    if (enableWordTimeOffsets_ != false) {
      output.writeBool(8, enableWordTimeOffsets_);
    }
    if (enableAutomaticPunctuation_ != false) {
      output.writeBool(11, enableAutomaticPunctuation_);
    }
    if (diarizationConfig_ != null) {
      output.writeMessage(16, getDiarizationConfig());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (encoding_ != ai.vernacular.speech.RecognitionConfig.AudioEncoding.ENCODING_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, encoding_);
    }
    if (sampleRateHertz_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, sampleRateHertz_);
    }
    if (!getLanguageCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, languageCode_);
    }
    if (maxAlternatives_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, maxAlternatives_);
    }
    for (int i = 0; i < speechContexts_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, speechContexts_.get(i));
    }
    if (audioChannelCount_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, audioChannelCount_);
    }
    if (enableSeparateRecognitionPerChannel_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(7, enableSeparateRecognitionPerChannel_);
    }
    if (enableWordTimeOffsets_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, enableWordTimeOffsets_);
    }
    if (enableAutomaticPunctuation_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, enableAutomaticPunctuation_);
    }
    if (diarizationConfig_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(16, getDiarizationConfig());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.vernacular.speech.RecognitionConfig)) {
      return super.equals(obj);
    }
    ai.vernacular.speech.RecognitionConfig other = (ai.vernacular.speech.RecognitionConfig) obj;

    if (encoding_ != other.encoding_) return false;
    if (getSampleRateHertz()
        != other.getSampleRateHertz()) return false;
    if (!getLanguageCode()
        .equals(other.getLanguageCode())) return false;
    if (getMaxAlternatives()
        != other.getMaxAlternatives()) return false;
    if (!getSpeechContextsList()
        .equals(other.getSpeechContextsList())) return false;
    if (getAudioChannelCount()
        != other.getAudioChannelCount()) return false;
    if (getEnableSeparateRecognitionPerChannel()
        != other.getEnableSeparateRecognitionPerChannel()) return false;
    if (getEnableWordTimeOffsets()
        != other.getEnableWordTimeOffsets()) return false;
    if (getEnableAutomaticPunctuation()
        != other.getEnableAutomaticPunctuation()) return false;
    if (hasDiarizationConfig() != other.hasDiarizationConfig()) return false;
    if (hasDiarizationConfig()) {
      if (!getDiarizationConfig()
          .equals(other.getDiarizationConfig())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENCODING_FIELD_NUMBER;
    hash = (53 * hash) + encoding_;
    hash = (37 * hash) + SAMPLE_RATE_HERTZ_FIELD_NUMBER;
    hash = (53 * hash) + getSampleRateHertz();
    hash = (37 * hash) + LANGUAGE_CODE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguageCode().hashCode();
    hash = (37 * hash) + MAX_ALTERNATIVES_FIELD_NUMBER;
    hash = (53 * hash) + getMaxAlternatives();
    if (getSpeechContextsCount() > 0) {
      hash = (37 * hash) + SPEECH_CONTEXTS_FIELD_NUMBER;
      hash = (53 * hash) + getSpeechContextsList().hashCode();
    }
    hash = (37 * hash) + AUDIO_CHANNEL_COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getAudioChannelCount();
    hash = (37 * hash) + ENABLE_SEPARATE_RECOGNITION_PER_CHANNEL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnableSeparateRecognitionPerChannel());
    hash = (37 * hash) + ENABLE_WORD_TIME_OFFSETS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnableWordTimeOffsets());
    hash = (37 * hash) + ENABLE_AUTOMATIC_PUNCTUATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnableAutomaticPunctuation());
    if (hasDiarizationConfig()) {
      hash = (37 * hash) + DIARIZATION_CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getDiarizationConfig().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.vernacular.speech.RecognitionConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.RecognitionConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.RecognitionConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.RecognitionConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.RecognitionConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.RecognitionConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.RecognitionConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.RecognitionConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.vernacular.speech.RecognitionConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.RecognitionConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.vernacular.speech.RecognitionConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.RecognitionConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.vernacular.speech.RecognitionConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Provides information to the recognizer that specifies how to process the request
   * </pre>
   *
   * Protobuf type {@code speech_to_text.RecognitionConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:speech_to_text.RecognitionConfig)
      ai.vernacular.speech.RecognitionConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_RecognitionConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_RecognitionConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.vernacular.speech.RecognitionConfig.class, ai.vernacular.speech.RecognitionConfig.Builder.class);
    }

    // Construct using ai.vernacular.speech.RecognitionConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSpeechContextsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      encoding_ = 0;

      sampleRateHertz_ = 0;

      languageCode_ = "";

      maxAlternatives_ = 0;

      if (speechContextsBuilder_ == null) {
        speechContexts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        speechContextsBuilder_.clear();
      }
      audioChannelCount_ = 0;

      enableSeparateRecognitionPerChannel_ = false;

      enableWordTimeOffsets_ = false;

      enableAutomaticPunctuation_ = false;

      if (diarizationConfigBuilder_ == null) {
        diarizationConfig_ = null;
      } else {
        diarizationConfig_ = null;
        diarizationConfigBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_RecognitionConfig_descriptor;
    }

    @java.lang.Override
    public ai.vernacular.speech.RecognitionConfig getDefaultInstanceForType() {
      return ai.vernacular.speech.RecognitionConfig.getDefaultInstance();
    }

    @java.lang.Override
    public ai.vernacular.speech.RecognitionConfig build() {
      ai.vernacular.speech.RecognitionConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.vernacular.speech.RecognitionConfig buildPartial() {
      ai.vernacular.speech.RecognitionConfig result = new ai.vernacular.speech.RecognitionConfig(this);
      int from_bitField0_ = bitField0_;
      result.encoding_ = encoding_;
      result.sampleRateHertz_ = sampleRateHertz_;
      result.languageCode_ = languageCode_;
      result.maxAlternatives_ = maxAlternatives_;
      if (speechContextsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          speechContexts_ = java.util.Collections.unmodifiableList(speechContexts_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.speechContexts_ = speechContexts_;
      } else {
        result.speechContexts_ = speechContextsBuilder_.build();
      }
      result.audioChannelCount_ = audioChannelCount_;
      result.enableSeparateRecognitionPerChannel_ = enableSeparateRecognitionPerChannel_;
      result.enableWordTimeOffsets_ = enableWordTimeOffsets_;
      result.enableAutomaticPunctuation_ = enableAutomaticPunctuation_;
      if (diarizationConfigBuilder_ == null) {
        result.diarizationConfig_ = diarizationConfig_;
      } else {
        result.diarizationConfig_ = diarizationConfigBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.vernacular.speech.RecognitionConfig) {
        return mergeFrom((ai.vernacular.speech.RecognitionConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.vernacular.speech.RecognitionConfig other) {
      if (other == ai.vernacular.speech.RecognitionConfig.getDefaultInstance()) return this;
      if (other.encoding_ != 0) {
        setEncodingValue(other.getEncodingValue());
      }
      if (other.getSampleRateHertz() != 0) {
        setSampleRateHertz(other.getSampleRateHertz());
      }
      if (!other.getLanguageCode().isEmpty()) {
        languageCode_ = other.languageCode_;
        onChanged();
      }
      if (other.getMaxAlternatives() != 0) {
        setMaxAlternatives(other.getMaxAlternatives());
      }
      if (speechContextsBuilder_ == null) {
        if (!other.speechContexts_.isEmpty()) {
          if (speechContexts_.isEmpty()) {
            speechContexts_ = other.speechContexts_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSpeechContextsIsMutable();
            speechContexts_.addAll(other.speechContexts_);
          }
          onChanged();
        }
      } else {
        if (!other.speechContexts_.isEmpty()) {
          if (speechContextsBuilder_.isEmpty()) {
            speechContextsBuilder_.dispose();
            speechContextsBuilder_ = null;
            speechContexts_ = other.speechContexts_;
            bitField0_ = (bitField0_ & ~0x00000001);
            speechContextsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSpeechContextsFieldBuilder() : null;
          } else {
            speechContextsBuilder_.addAllMessages(other.speechContexts_);
          }
        }
      }
      if (other.getAudioChannelCount() != 0) {
        setAudioChannelCount(other.getAudioChannelCount());
      }
      if (other.getEnableSeparateRecognitionPerChannel() != false) {
        setEnableSeparateRecognitionPerChannel(other.getEnableSeparateRecognitionPerChannel());
      }
      if (other.getEnableWordTimeOffsets() != false) {
        setEnableWordTimeOffsets(other.getEnableWordTimeOffsets());
      }
      if (other.getEnableAutomaticPunctuation() != false) {
        setEnableAutomaticPunctuation(other.getEnableAutomaticPunctuation());
      }
      if (other.hasDiarizationConfig()) {
        mergeDiarizationConfig(other.getDiarizationConfig());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.vernacular.speech.RecognitionConfig parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.vernacular.speech.RecognitionConfig) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int encoding_ = 0;
    /**
     * <code>.speech_to_text.RecognitionConfig.AudioEncoding encoding = 1;</code>
     * @return The enum numeric value on the wire for encoding.
     */
    public int getEncodingValue() {
      return encoding_;
    }
    /**
     * <code>.speech_to_text.RecognitionConfig.AudioEncoding encoding = 1;</code>
     * @param value The enum numeric value on the wire for encoding to set.
     * @return This builder for chaining.
     */
    public Builder setEncodingValue(int value) {
      encoding_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.speech_to_text.RecognitionConfig.AudioEncoding encoding = 1;</code>
     * @return The encoding.
     */
    public ai.vernacular.speech.RecognitionConfig.AudioEncoding getEncoding() {
      @SuppressWarnings("deprecation")
      ai.vernacular.speech.RecognitionConfig.AudioEncoding result = ai.vernacular.speech.RecognitionConfig.AudioEncoding.valueOf(encoding_);
      return result == null ? ai.vernacular.speech.RecognitionConfig.AudioEncoding.UNRECOGNIZED : result;
    }
    /**
     * <code>.speech_to_text.RecognitionConfig.AudioEncoding encoding = 1;</code>
     * @param value The encoding to set.
     * @return This builder for chaining.
     */
    public Builder setEncoding(ai.vernacular.speech.RecognitionConfig.AudioEncoding value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      encoding_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.speech_to_text.RecognitionConfig.AudioEncoding encoding = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncoding() {
      
      encoding_ = 0;
      onChanged();
      return this;
    }

    private int sampleRateHertz_ ;
    /**
     * <pre>
     * Valid values are: 8000-48000.
     * </pre>
     *
     * <code>int32 sample_rate_hertz = 2;</code>
     * @return The sampleRateHertz.
     */
    public int getSampleRateHertz() {
      return sampleRateHertz_;
    }
    /**
     * <pre>
     * Valid values are: 8000-48000.
     * </pre>
     *
     * <code>int32 sample_rate_hertz = 2;</code>
     * @param value The sampleRateHertz to set.
     * @return This builder for chaining.
     */
    public Builder setSampleRateHertz(int value) {
      
      sampleRateHertz_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Valid values are: 8000-48000.
     * </pre>
     *
     * <code>int32 sample_rate_hertz = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSampleRateHertz() {
      
      sampleRateHertz_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object languageCode_ = "";
    /**
     * <code>string language_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The languageCode.
     */
    public java.lang.String getLanguageCode() {
      java.lang.Object ref = languageCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languageCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string language_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The bytes for languageCode.
     */
    public com.google.protobuf.ByteString
        getLanguageCodeBytes() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string language_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The languageCode to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      languageCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string language_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguageCode() {
      
      languageCode_ = getDefaultInstance().getLanguageCode();
      onChanged();
      return this;
    }
    /**
     * <code>string language_code = 3 [(.google.api.field_behavior) = REQUIRED];</code>
     * @param value The bytes for languageCode to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      languageCode_ = value;
      onChanged();
      return this;
    }

    private int maxAlternatives_ ;
    /**
     * <code>int32 max_alternatives = 4;</code>
     * @return The maxAlternatives.
     */
    public int getMaxAlternatives() {
      return maxAlternatives_;
    }
    /**
     * <code>int32 max_alternatives = 4;</code>
     * @param value The maxAlternatives to set.
     * @return This builder for chaining.
     */
    public Builder setMaxAlternatives(int value) {
      
      maxAlternatives_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_alternatives = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxAlternatives() {
      
      maxAlternatives_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<ai.vernacular.speech.SpeechContext> speechContexts_ =
      java.util.Collections.emptyList();
    private void ensureSpeechContextsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        speechContexts_ = new java.util.ArrayList<ai.vernacular.speech.SpeechContext>(speechContexts_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ai.vernacular.speech.SpeechContext, ai.vernacular.speech.SpeechContext.Builder, ai.vernacular.speech.SpeechContextOrBuilder> speechContextsBuilder_;

    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public java.util.List<ai.vernacular.speech.SpeechContext> getSpeechContextsList() {
      if (speechContextsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(speechContexts_);
      } else {
        return speechContextsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public int getSpeechContextsCount() {
      if (speechContextsBuilder_ == null) {
        return speechContexts_.size();
      } else {
        return speechContextsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public ai.vernacular.speech.SpeechContext getSpeechContexts(int index) {
      if (speechContextsBuilder_ == null) {
        return speechContexts_.get(index);
      } else {
        return speechContextsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public Builder setSpeechContexts(
        int index, ai.vernacular.speech.SpeechContext value) {
      if (speechContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpeechContextsIsMutable();
        speechContexts_.set(index, value);
        onChanged();
      } else {
        speechContextsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public Builder setSpeechContexts(
        int index, ai.vernacular.speech.SpeechContext.Builder builderForValue) {
      if (speechContextsBuilder_ == null) {
        ensureSpeechContextsIsMutable();
        speechContexts_.set(index, builderForValue.build());
        onChanged();
      } else {
        speechContextsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public Builder addSpeechContexts(ai.vernacular.speech.SpeechContext value) {
      if (speechContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpeechContextsIsMutable();
        speechContexts_.add(value);
        onChanged();
      } else {
        speechContextsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public Builder addSpeechContexts(
        int index, ai.vernacular.speech.SpeechContext value) {
      if (speechContextsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpeechContextsIsMutable();
        speechContexts_.add(index, value);
        onChanged();
      } else {
        speechContextsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public Builder addSpeechContexts(
        ai.vernacular.speech.SpeechContext.Builder builderForValue) {
      if (speechContextsBuilder_ == null) {
        ensureSpeechContextsIsMutable();
        speechContexts_.add(builderForValue.build());
        onChanged();
      } else {
        speechContextsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public Builder addSpeechContexts(
        int index, ai.vernacular.speech.SpeechContext.Builder builderForValue) {
      if (speechContextsBuilder_ == null) {
        ensureSpeechContextsIsMutable();
        speechContexts_.add(index, builderForValue.build());
        onChanged();
      } else {
        speechContextsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public Builder addAllSpeechContexts(
        java.lang.Iterable<? extends ai.vernacular.speech.SpeechContext> values) {
      if (speechContextsBuilder_ == null) {
        ensureSpeechContextsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, speechContexts_);
        onChanged();
      } else {
        speechContextsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public Builder clearSpeechContexts() {
      if (speechContextsBuilder_ == null) {
        speechContexts_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        speechContextsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public Builder removeSpeechContexts(int index) {
      if (speechContextsBuilder_ == null) {
        ensureSpeechContextsIsMutable();
        speechContexts_.remove(index);
        onChanged();
      } else {
        speechContextsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public ai.vernacular.speech.SpeechContext.Builder getSpeechContextsBuilder(
        int index) {
      return getSpeechContextsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public ai.vernacular.speech.SpeechContextOrBuilder getSpeechContextsOrBuilder(
        int index) {
      if (speechContextsBuilder_ == null) {
        return speechContexts_.get(index);  } else {
        return speechContextsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public java.util.List<? extends ai.vernacular.speech.SpeechContextOrBuilder> 
         getSpeechContextsOrBuilderList() {
      if (speechContextsBuilder_ != null) {
        return speechContextsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(speechContexts_);
      }
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public ai.vernacular.speech.SpeechContext.Builder addSpeechContextsBuilder() {
      return getSpeechContextsFieldBuilder().addBuilder(
          ai.vernacular.speech.SpeechContext.getDefaultInstance());
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public ai.vernacular.speech.SpeechContext.Builder addSpeechContextsBuilder(
        int index) {
      return getSpeechContextsFieldBuilder().addBuilder(
          index, ai.vernacular.speech.SpeechContext.getDefaultInstance());
    }
    /**
     * <code>repeated .speech_to_text.SpeechContext speech_contexts = 5;</code>
     */
    public java.util.List<ai.vernacular.speech.SpeechContext.Builder> 
         getSpeechContextsBuilderList() {
      return getSpeechContextsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ai.vernacular.speech.SpeechContext, ai.vernacular.speech.SpeechContext.Builder, ai.vernacular.speech.SpeechContextOrBuilder> 
        getSpeechContextsFieldBuilder() {
      if (speechContextsBuilder_ == null) {
        speechContextsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ai.vernacular.speech.SpeechContext, ai.vernacular.speech.SpeechContext.Builder, ai.vernacular.speech.SpeechContextOrBuilder>(
                speechContexts_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        speechContexts_ = null;
      }
      return speechContextsBuilder_;
    }

    private int audioChannelCount_ ;
    /**
     * <code>int32 audio_channel_count = 6;</code>
     * @return The audioChannelCount.
     */
    public int getAudioChannelCount() {
      return audioChannelCount_;
    }
    /**
     * <code>int32 audio_channel_count = 6;</code>
     * @param value The audioChannelCount to set.
     * @return This builder for chaining.
     */
    public Builder setAudioChannelCount(int value) {
      
      audioChannelCount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 audio_channel_count = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudioChannelCount() {
      
      audioChannelCount_ = 0;
      onChanged();
      return this;
    }

    private boolean enableSeparateRecognitionPerChannel_ ;
    /**
     * <code>bool enable_separate_recognition_per_channel = 7;</code>
     * @return The enableSeparateRecognitionPerChannel.
     */
    public boolean getEnableSeparateRecognitionPerChannel() {
      return enableSeparateRecognitionPerChannel_;
    }
    /**
     * <code>bool enable_separate_recognition_per_channel = 7;</code>
     * @param value The enableSeparateRecognitionPerChannel to set.
     * @return This builder for chaining.
     */
    public Builder setEnableSeparateRecognitionPerChannel(boolean value) {
      
      enableSeparateRecognitionPerChannel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool enable_separate_recognition_per_channel = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnableSeparateRecognitionPerChannel() {
      
      enableSeparateRecognitionPerChannel_ = false;
      onChanged();
      return this;
    }

    private boolean enableWordTimeOffsets_ ;
    /**
     * <code>bool enable_word_time_offsets = 8;</code>
     * @return The enableWordTimeOffsets.
     */
    public boolean getEnableWordTimeOffsets() {
      return enableWordTimeOffsets_;
    }
    /**
     * <code>bool enable_word_time_offsets = 8;</code>
     * @param value The enableWordTimeOffsets to set.
     * @return This builder for chaining.
     */
    public Builder setEnableWordTimeOffsets(boolean value) {
      
      enableWordTimeOffsets_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool enable_word_time_offsets = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnableWordTimeOffsets() {
      
      enableWordTimeOffsets_ = false;
      onChanged();
      return this;
    }

    private boolean enableAutomaticPunctuation_ ;
    /**
     * <code>bool enable_automatic_punctuation = 11;</code>
     * @return The enableAutomaticPunctuation.
     */
    public boolean getEnableAutomaticPunctuation() {
      return enableAutomaticPunctuation_;
    }
    /**
     * <code>bool enable_automatic_punctuation = 11;</code>
     * @param value The enableAutomaticPunctuation to set.
     * @return This builder for chaining.
     */
    public Builder setEnableAutomaticPunctuation(boolean value) {
      
      enableAutomaticPunctuation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool enable_automatic_punctuation = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearEnableAutomaticPunctuation() {
      
      enableAutomaticPunctuation_ = false;
      onChanged();
      return this;
    }

    private ai.vernacular.speech.SpeakerDiarizationConfig diarizationConfig_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.vernacular.speech.SpeakerDiarizationConfig, ai.vernacular.speech.SpeakerDiarizationConfig.Builder, ai.vernacular.speech.SpeakerDiarizationConfigOrBuilder> diarizationConfigBuilder_;
    /**
     * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
     * @return Whether the diarizationConfig field is set.
     */
    public boolean hasDiarizationConfig() {
      return diarizationConfigBuilder_ != null || diarizationConfig_ != null;
    }
    /**
     * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
     * @return The diarizationConfig.
     */
    public ai.vernacular.speech.SpeakerDiarizationConfig getDiarizationConfig() {
      if (diarizationConfigBuilder_ == null) {
        return diarizationConfig_ == null ? ai.vernacular.speech.SpeakerDiarizationConfig.getDefaultInstance() : diarizationConfig_;
      } else {
        return diarizationConfigBuilder_.getMessage();
      }
    }
    /**
     * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
     */
    public Builder setDiarizationConfig(ai.vernacular.speech.SpeakerDiarizationConfig value) {
      if (diarizationConfigBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        diarizationConfig_ = value;
        onChanged();
      } else {
        diarizationConfigBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
     */
    public Builder setDiarizationConfig(
        ai.vernacular.speech.SpeakerDiarizationConfig.Builder builderForValue) {
      if (diarizationConfigBuilder_ == null) {
        diarizationConfig_ = builderForValue.build();
        onChanged();
      } else {
        diarizationConfigBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
     */
    public Builder mergeDiarizationConfig(ai.vernacular.speech.SpeakerDiarizationConfig value) {
      if (diarizationConfigBuilder_ == null) {
        if (diarizationConfig_ != null) {
          diarizationConfig_ =
            ai.vernacular.speech.SpeakerDiarizationConfig.newBuilder(diarizationConfig_).mergeFrom(value).buildPartial();
        } else {
          diarizationConfig_ = value;
        }
        onChanged();
      } else {
        diarizationConfigBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
     */
    public Builder clearDiarizationConfig() {
      if (diarizationConfigBuilder_ == null) {
        diarizationConfig_ = null;
        onChanged();
      } else {
        diarizationConfig_ = null;
        diarizationConfigBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
     */
    public ai.vernacular.speech.SpeakerDiarizationConfig.Builder getDiarizationConfigBuilder() {
      
      onChanged();
      return getDiarizationConfigFieldBuilder().getBuilder();
    }
    /**
     * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
     */
    public ai.vernacular.speech.SpeakerDiarizationConfigOrBuilder getDiarizationConfigOrBuilder() {
      if (diarizationConfigBuilder_ != null) {
        return diarizationConfigBuilder_.getMessageOrBuilder();
      } else {
        return diarizationConfig_ == null ?
            ai.vernacular.speech.SpeakerDiarizationConfig.getDefaultInstance() : diarizationConfig_;
      }
    }
    /**
     * <code>.speech_to_text.SpeakerDiarizationConfig diarization_config = 16;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.vernacular.speech.SpeakerDiarizationConfig, ai.vernacular.speech.SpeakerDiarizationConfig.Builder, ai.vernacular.speech.SpeakerDiarizationConfigOrBuilder> 
        getDiarizationConfigFieldBuilder() {
      if (diarizationConfigBuilder_ == null) {
        diarizationConfigBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.vernacular.speech.SpeakerDiarizationConfig, ai.vernacular.speech.SpeakerDiarizationConfig.Builder, ai.vernacular.speech.SpeakerDiarizationConfigOrBuilder>(
                getDiarizationConfig(),
                getParentForChildren(),
                isClean());
        diarizationConfig_ = null;
      }
      return diarizationConfigBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:speech_to_text.RecognitionConfig)
  }

  // @@protoc_insertion_point(class_scope:speech_to_text.RecognitionConfig)
  private static final ai.vernacular.speech.RecognitionConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.vernacular.speech.RecognitionConfig();
  }

  public static ai.vernacular.speech.RecognitionConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RecognitionConfig>
      PARSER = new com.google.protobuf.AbstractParser<RecognitionConfig>() {
    @java.lang.Override
    public RecognitionConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RecognitionConfig(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RecognitionConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RecognitionConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.vernacular.speech.RecognitionConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

