// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

public interface SpeechOperationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech_to_text.SpeechOperationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * name of the speech operation
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * name of the speech operation
   * </pre>
   *
   * <code>string name = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
