// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

/**
 * Protobuf type {@code speech_to_text.SpeechOperation}
 */
public  final class SpeechOperation extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:speech_to_text.SpeechOperation)
    SpeechOperationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpeechOperation.newBuilder() to construct.
  private SpeechOperation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpeechOperation() {
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SpeechOperation();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpeechOperation(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 16: {

            done_ = input.readBool();
            break;
          }
          case 26: {
            com.google.rpc.Status.Builder subBuilder = null;
            if (resultCase_ == 3) {
              subBuilder = ((com.google.rpc.Status) result_).toBuilder();
            }
            result_ =
                input.readMessage(com.google.rpc.Status.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.google.rpc.Status) result_);
              result_ = subBuilder.buildPartial();
            }
            resultCase_ = 3;
            break;
          }
          case 34: {
            ai.vernacular.speech.LongRunningRecognizeResponse.Builder subBuilder = null;
            if (resultCase_ == 4) {
              subBuilder = ((ai.vernacular.speech.LongRunningRecognizeResponse) result_).toBuilder();
            }
            result_ =
                input.readMessage(ai.vernacular.speech.LongRunningRecognizeResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((ai.vernacular.speech.LongRunningRecognizeResponse) result_);
              result_ = subBuilder.buildPartial();
            }
            resultCase_ = 4;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_SpeechOperation_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_SpeechOperation_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.vernacular.speech.SpeechOperation.class, ai.vernacular.speech.SpeechOperation.Builder.class);
  }

  private int resultCase_ = 0;
  private java.lang.Object result_;
  public enum ResultCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    ERROR(3),
    RESPONSE(4),
    RESULT_NOT_SET(0);
    private final int value;
    private ResultCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static ResultCase forNumber(int value) {
      switch (value) {
        case 3: return ERROR;
        case 4: return RESPONSE;
        case 0: return RESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ResultCase
  getResultCase() {
    return ResultCase.forNumber(
        resultCase_);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DONE_FIELD_NUMBER = 2;
  private boolean done_;
  /**
   * <code>bool done = 2;</code>
   * @return The done.
   */
  public boolean getDone() {
    return done_;
  }

  public static final int ERROR_FIELD_NUMBER = 3;
  /**
   * <pre>
   * If set, returns a [google.rpc.Status][google.rpc.Status] message that
   * specifies the error for the operation.
   * </pre>
   *
   * <code>.google.rpc.Status error = 3;</code>
   * @return Whether the error field is set.
   */
  public boolean hasError() {
    return resultCase_ == 3;
  }
  /**
   * <pre>
   * If set, returns a [google.rpc.Status][google.rpc.Status] message that
   * specifies the error for the operation.
   * </pre>
   *
   * <code>.google.rpc.Status error = 3;</code>
   * @return The error.
   */
  public com.google.rpc.Status getError() {
    if (resultCase_ == 3) {
       return (com.google.rpc.Status) result_;
    }
    return com.google.rpc.Status.getDefaultInstance();
  }
  /**
   * <pre>
   * If set, returns a [google.rpc.Status][google.rpc.Status] message that
   * specifies the error for the operation.
   * </pre>
   *
   * <code>.google.rpc.Status error = 3;</code>
   */
  public com.google.rpc.StatusOrBuilder getErrorOrBuilder() {
    if (resultCase_ == 3) {
       return (com.google.rpc.Status) result_;
    }
    return com.google.rpc.Status.getDefaultInstance();
  }

  public static final int RESPONSE_FIELD_NUMBER = 4;
  /**
   * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
   * @return Whether the response field is set.
   */
  public boolean hasResponse() {
    return resultCase_ == 4;
  }
  /**
   * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
   * @return The response.
   */
  public ai.vernacular.speech.LongRunningRecognizeResponse getResponse() {
    if (resultCase_ == 4) {
       return (ai.vernacular.speech.LongRunningRecognizeResponse) result_;
    }
    return ai.vernacular.speech.LongRunningRecognizeResponse.getDefaultInstance();
  }
  /**
   * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
   */
  public ai.vernacular.speech.LongRunningRecognizeResponseOrBuilder getResponseOrBuilder() {
    if (resultCase_ == 4) {
       return (ai.vernacular.speech.LongRunningRecognizeResponse) result_;
    }
    return ai.vernacular.speech.LongRunningRecognizeResponse.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (done_ != false) {
      output.writeBool(2, done_);
    }
    if (resultCase_ == 3) {
      output.writeMessage(3, (com.google.rpc.Status) result_);
    }
    if (resultCase_ == 4) {
      output.writeMessage(4, (ai.vernacular.speech.LongRunningRecognizeResponse) result_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (done_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, done_);
    }
    if (resultCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.google.rpc.Status) result_);
    }
    if (resultCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (ai.vernacular.speech.LongRunningRecognizeResponse) result_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.vernacular.speech.SpeechOperation)) {
      return super.equals(obj);
    }
    ai.vernacular.speech.SpeechOperation other = (ai.vernacular.speech.SpeechOperation) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (getDone()
        != other.getDone()) return false;
    if (!getResultCase().equals(other.getResultCase())) return false;
    switch (resultCase_) {
      case 3:
        if (!getError()
            .equals(other.getError())) return false;
        break;
      case 4:
        if (!getResponse()
            .equals(other.getResponse())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DONE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDone());
    switch (resultCase_) {
      case 3:
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + getError().hashCode();
        break;
      case 4:
        hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getResponse().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.vernacular.speech.SpeechOperation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.SpeechOperation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.SpeechOperation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.SpeechOperation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.SpeechOperation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.SpeechOperation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.SpeechOperation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.SpeechOperation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.vernacular.speech.SpeechOperation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.SpeechOperation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.vernacular.speech.SpeechOperation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.SpeechOperation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.vernacular.speech.SpeechOperation prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code speech_to_text.SpeechOperation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:speech_to_text.SpeechOperation)
      ai.vernacular.speech.SpeechOperationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_SpeechOperation_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_SpeechOperation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.vernacular.speech.SpeechOperation.class, ai.vernacular.speech.SpeechOperation.Builder.class);
    }

    // Construct using ai.vernacular.speech.SpeechOperation.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      done_ = false;

      resultCase_ = 0;
      result_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_SpeechOperation_descriptor;
    }

    @java.lang.Override
    public ai.vernacular.speech.SpeechOperation getDefaultInstanceForType() {
      return ai.vernacular.speech.SpeechOperation.getDefaultInstance();
    }

    @java.lang.Override
    public ai.vernacular.speech.SpeechOperation build() {
      ai.vernacular.speech.SpeechOperation result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.vernacular.speech.SpeechOperation buildPartial() {
      ai.vernacular.speech.SpeechOperation result = new ai.vernacular.speech.SpeechOperation(this);
      result.name_ = name_;
      result.done_ = done_;
      if (resultCase_ == 3) {
        if (errorBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = errorBuilder_.build();
        }
      }
      if (resultCase_ == 4) {
        if (responseBuilder_ == null) {
          result.result_ = result_;
        } else {
          result.result_ = responseBuilder_.build();
        }
      }
      result.resultCase_ = resultCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.vernacular.speech.SpeechOperation) {
        return mergeFrom((ai.vernacular.speech.SpeechOperation)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.vernacular.speech.SpeechOperation other) {
      if (other == ai.vernacular.speech.SpeechOperation.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getDone() != false) {
        setDone(other.getDone());
      }
      switch (other.getResultCase()) {
        case ERROR: {
          mergeError(other.getError());
          break;
        }
        case RESPONSE: {
          mergeResponse(other.getResponse());
          break;
        }
        case RESULT_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.vernacular.speech.SpeechOperation parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.vernacular.speech.SpeechOperation) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int resultCase_ = 0;
    private java.lang.Object result_;
    public ResultCase
        getResultCase() {
      return ResultCase.forNumber(
          resultCase_);
    }

    public Builder clearResult() {
      resultCase_ = 0;
      result_ = null;
      onChanged();
      return this;
    }


    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private boolean done_ ;
    /**
     * <code>bool done = 2;</code>
     * @return The done.
     */
    public boolean getDone() {
      return done_;
    }
    /**
     * <code>bool done = 2;</code>
     * @param value The done to set.
     * @return This builder for chaining.
     */
    public Builder setDone(boolean value) {
      
      done_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool done = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDone() {
      
      done_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> errorBuilder_;
    /**
     * <pre>
     * If set, returns a [google.rpc.Status][google.rpc.Status] message that
     * specifies the error for the operation.
     * </pre>
     *
     * <code>.google.rpc.Status error = 3;</code>
     * @return Whether the error field is set.
     */
    public boolean hasError() {
      return resultCase_ == 3;
    }
    /**
     * <pre>
     * If set, returns a [google.rpc.Status][google.rpc.Status] message that
     * specifies the error for the operation.
     * </pre>
     *
     * <code>.google.rpc.Status error = 3;</code>
     * @return The error.
     */
    public com.google.rpc.Status getError() {
      if (errorBuilder_ == null) {
        if (resultCase_ == 3) {
          return (com.google.rpc.Status) result_;
        }
        return com.google.rpc.Status.getDefaultInstance();
      } else {
        if (resultCase_ == 3) {
          return errorBuilder_.getMessage();
        }
        return com.google.rpc.Status.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * If set, returns a [google.rpc.Status][google.rpc.Status] message that
     * specifies the error for the operation.
     * </pre>
     *
     * <code>.google.rpc.Status error = 3;</code>
     */
    public Builder setError(com.google.rpc.Status value) {
      if (errorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        errorBuilder_.setMessage(value);
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * If set, returns a [google.rpc.Status][google.rpc.Status] message that
     * specifies the error for the operation.
     * </pre>
     *
     * <code>.google.rpc.Status error = 3;</code>
     */
    public Builder setError(
        com.google.rpc.Status.Builder builderForValue) {
      if (errorBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        errorBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * If set, returns a [google.rpc.Status][google.rpc.Status] message that
     * specifies the error for the operation.
     * </pre>
     *
     * <code>.google.rpc.Status error = 3;</code>
     */
    public Builder mergeError(com.google.rpc.Status value) {
      if (errorBuilder_ == null) {
        if (resultCase_ == 3 &&
            result_ != com.google.rpc.Status.getDefaultInstance()) {
          result_ = com.google.rpc.Status.newBuilder((com.google.rpc.Status) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 3) {
          errorBuilder_.mergeFrom(value);
        }
        errorBuilder_.setMessage(value);
      }
      resultCase_ = 3;
      return this;
    }
    /**
     * <pre>
     * If set, returns a [google.rpc.Status][google.rpc.Status] message that
     * specifies the error for the operation.
     * </pre>
     *
     * <code>.google.rpc.Status error = 3;</code>
     */
    public Builder clearError() {
      if (errorBuilder_ == null) {
        if (resultCase_ == 3) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 3) {
          resultCase_ = 0;
          result_ = null;
        }
        errorBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * If set, returns a [google.rpc.Status][google.rpc.Status] message that
     * specifies the error for the operation.
     * </pre>
     *
     * <code>.google.rpc.Status error = 3;</code>
     */
    public com.google.rpc.Status.Builder getErrorBuilder() {
      return getErrorFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * If set, returns a [google.rpc.Status][google.rpc.Status] message that
     * specifies the error for the operation.
     * </pre>
     *
     * <code>.google.rpc.Status error = 3;</code>
     */
    public com.google.rpc.StatusOrBuilder getErrorOrBuilder() {
      if ((resultCase_ == 3) && (errorBuilder_ != null)) {
        return errorBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 3) {
          return (com.google.rpc.Status) result_;
        }
        return com.google.rpc.Status.getDefaultInstance();
      }
    }
    /**
     * <pre>
     * If set, returns a [google.rpc.Status][google.rpc.Status] message that
     * specifies the error for the operation.
     * </pre>
     *
     * <code>.google.rpc.Status error = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder> 
        getErrorFieldBuilder() {
      if (errorBuilder_ == null) {
        if (!(resultCase_ == 3)) {
          result_ = com.google.rpc.Status.getDefaultInstance();
        }
        errorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.rpc.Status, com.google.rpc.Status.Builder, com.google.rpc.StatusOrBuilder>(
                (com.google.rpc.Status) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 3;
      onChanged();;
      return errorBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        ai.vernacular.speech.LongRunningRecognizeResponse, ai.vernacular.speech.LongRunningRecognizeResponse.Builder, ai.vernacular.speech.LongRunningRecognizeResponseOrBuilder> responseBuilder_;
    /**
     * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
     * @return Whether the response field is set.
     */
    public boolean hasResponse() {
      return resultCase_ == 4;
    }
    /**
     * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
     * @return The response.
     */
    public ai.vernacular.speech.LongRunningRecognizeResponse getResponse() {
      if (responseBuilder_ == null) {
        if (resultCase_ == 4) {
          return (ai.vernacular.speech.LongRunningRecognizeResponse) result_;
        }
        return ai.vernacular.speech.LongRunningRecognizeResponse.getDefaultInstance();
      } else {
        if (resultCase_ == 4) {
          return responseBuilder_.getMessage();
        }
        return ai.vernacular.speech.LongRunningRecognizeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
     */
    public Builder setResponse(ai.vernacular.speech.LongRunningRecognizeResponse value) {
      if (responseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        responseBuilder_.setMessage(value);
      }
      resultCase_ = 4;
      return this;
    }
    /**
     * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
     */
    public Builder setResponse(
        ai.vernacular.speech.LongRunningRecognizeResponse.Builder builderForValue) {
      if (responseBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        responseBuilder_.setMessage(builderForValue.build());
      }
      resultCase_ = 4;
      return this;
    }
    /**
     * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
     */
    public Builder mergeResponse(ai.vernacular.speech.LongRunningRecognizeResponse value) {
      if (responseBuilder_ == null) {
        if (resultCase_ == 4 &&
            result_ != ai.vernacular.speech.LongRunningRecognizeResponse.getDefaultInstance()) {
          result_ = ai.vernacular.speech.LongRunningRecognizeResponse.newBuilder((ai.vernacular.speech.LongRunningRecognizeResponse) result_)
              .mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        if (resultCase_ == 4) {
          responseBuilder_.mergeFrom(value);
        }
        responseBuilder_.setMessage(value);
      }
      resultCase_ = 4;
      return this;
    }
    /**
     * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
     */
    public Builder clearResponse() {
      if (responseBuilder_ == null) {
        if (resultCase_ == 4) {
          resultCase_ = 0;
          result_ = null;
          onChanged();
        }
      } else {
        if (resultCase_ == 4) {
          resultCase_ = 0;
          result_ = null;
        }
        responseBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
     */
    public ai.vernacular.speech.LongRunningRecognizeResponse.Builder getResponseBuilder() {
      return getResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
     */
    public ai.vernacular.speech.LongRunningRecognizeResponseOrBuilder getResponseOrBuilder() {
      if ((resultCase_ == 4) && (responseBuilder_ != null)) {
        return responseBuilder_.getMessageOrBuilder();
      } else {
        if (resultCase_ == 4) {
          return (ai.vernacular.speech.LongRunningRecognizeResponse) result_;
        }
        return ai.vernacular.speech.LongRunningRecognizeResponse.getDefaultInstance();
      }
    }
    /**
     * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.vernacular.speech.LongRunningRecognizeResponse, ai.vernacular.speech.LongRunningRecognizeResponse.Builder, ai.vernacular.speech.LongRunningRecognizeResponseOrBuilder> 
        getResponseFieldBuilder() {
      if (responseBuilder_ == null) {
        if (!(resultCase_ == 4)) {
          result_ = ai.vernacular.speech.LongRunningRecognizeResponse.getDefaultInstance();
        }
        responseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.vernacular.speech.LongRunningRecognizeResponse, ai.vernacular.speech.LongRunningRecognizeResponse.Builder, ai.vernacular.speech.LongRunningRecognizeResponseOrBuilder>(
                (ai.vernacular.speech.LongRunningRecognizeResponse) result_,
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      resultCase_ = 4;
      onChanged();;
      return responseBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:speech_to_text.SpeechOperation)
  }

  // @@protoc_insertion_point(class_scope:speech_to_text.SpeechOperation)
  private static final ai.vernacular.speech.SpeechOperation DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.vernacular.speech.SpeechOperation();
  }

  public static ai.vernacular.speech.SpeechOperation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpeechOperation>
      PARSER = new com.google.protobuf.AbstractParser<SpeechOperation>() {
    @java.lang.Override
    public SpeechOperation parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpeechOperation(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpeechOperation> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SpeechOperation> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.vernacular.speech.SpeechOperation getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

