// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

public final class SpeechToTextProto {
  private SpeechToTextProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_RecognizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_RecognizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_LongRunningRecognizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_LongRunningRecognizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_SpeechOperationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_SpeechOperationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_StreamingRecognizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_StreamingRecognizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_StreamingRecognitionConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_StreamingRecognitionConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_RecognitionConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_RecognitionConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_SpeechContext_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_SpeechContext_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_SpeakerDiarizationConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_SpeakerDiarizationConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_RecognitionAudio_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_RecognitionAudio_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_RecognizeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_RecognizeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_LongRunningRecognizeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_LongRunningRecognizeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_StreamingRecognizeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_StreamingRecognizeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_SpeechRecognitionResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_SpeechRecognitionResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_StreamingRecognitionResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_StreamingRecognitionResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_SpeechRecognitionAlternative_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_SpeechRecognitionAlternative_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_WordInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_WordInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_speech_to_text_SpeechOperation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_speech_to_text_SpeechOperation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024speech-to-text.proto\022\016speech_to_text\032\034" +
      "google/api/annotations.proto\032\027google/api" +
      "/client.proto\032\037google/api/field_behavior" +
      ".proto\032\027google/rpc/status.proto\"\221\001\n\020Reco" +
      "gnizeRequest\0226\n\006config\030\001 \001(\0132!.speech_to" +
      "_text.RecognitionConfigB\003\340A\002\0224\n\005audio\030\002 " +
      "\001(\0132 .speech_to_text.RecognitionAudioB\003\340" +
      "A\002\022\017\n\007segment\030\020 \001(\t\"\260\001\n\033LongRunningRecog" +
      "nizeRequest\0226\n\006config\030\001 \001(\0132!.speech_to_" +
      "text.RecognitionConfigB\003\340A\002\0224\n\005audio\030\002 \001" +
      "(\0132 .speech_to_text.RecognitionAudioB\003\340A" +
      "\002\022\022\n\nresult_url\030\013 \001(\t\022\017\n\007segment\030\020 \001(\t\"+" +
      "\n\026SpeechOperationRequest\022\021\n\004name\030\001 \001(\tB\003" +
      "\340A\002\"\221\001\n\031StreamingRecognizeRequest\022F\n\020str" +
      "eaming_config\030\001 \001(\0132*.speech_to_text.Str" +
      "eamingRecognitionConfigH\000\022\027\n\raudio_conte" +
      "nt\030\002 \001(\014H\000B\023\n\021streaming_request\"m\n\032Strea" +
      "mingRecognitionConfig\0226\n\006config\030\001 \001(\0132!." +
      "speech_to_text.RecognitionConfigB\003\340A\002\022\027\n" +
      "\017interim_results\030\002 \001(\010\"\207\004\n\021RecognitionCo" +
      "nfig\022A\n\010encoding\030\001 \001(\0162/.speech_to_text." +
      "RecognitionConfig.AudioEncoding\022\031\n\021sampl" +
      "e_rate_hertz\030\002 \001(\005\022\032\n\rlanguage_code\030\003 \001(" +
      "\tB\003\340A\002\022\030\n\020max_alternatives\030\004 \001(\005\0226\n\017spee" +
      "ch_contexts\030\005 \003(\0132\035.speech_to_text.Speec" +
      "hContext\022\033\n\023audio_channel_count\030\006 \001(\005\022/\n" +
      "\'enable_separate_recognition_per_channel" +
      "\030\007 \001(\010\022 \n\030enable_word_time_offsets\030\010 \001(\010" +
      "\022$\n\034enable_automatic_punctuation\030\013 \001(\010\022D" +
      "\n\022diarization_config\030\020 \001(\0132(.speech_to_t" +
      "ext.SpeakerDiarizationConfig\"J\n\rAudioEnc" +
      "oding\022\030\n\024ENCODING_UNSPECIFIED\020\000\022\014\n\010LINEA" +
      "R16\020\001\022\010\n\004FLAC\020\002\022\007\n\003MP3\020\003\" \n\rSpeechContex" +
      "t\022\017\n\007phrases\030\001 \003(\t\"t\n\030SpeakerDiarization" +
      "Config\022\"\n\032enable_speaker_diarization\030\001 \001" +
      "(\010\022\031\n\021min_speaker_count\030\002 \001(\005\022\031\n\021max_spe" +
      "aker_count\030\003 \001(\005\"D\n\020RecognitionAudio\022\021\n\007" +
      "content\030\001 \001(\014H\000\022\r\n\003uri\030\002 \001(\tH\000B\016\n\014audio_" +
      "source\"M\n\021RecognizeResponse\0228\n\007results\030\001" +
      " \003(\0132\'.speech_to_text.SpeechRecognitionR" +
      "esult\"X\n\034LongRunningRecognizeResponse\0228\n" +
      "\007results\030\001 \003(\0132\'.speech_to_text.SpeechRe" +
      "cognitionResult\"|\n\032StreamingRecognizeRes" +
      "ponse\022!\n\005error\030\001 \001(\0132\022.google.rpc.Status" +
      "\022;\n\007results\030\002 \003(\0132*.speech_to_text.Strea" +
      "mingRecognitionResult\"r\n\027SpeechRecogniti" +
      "onResult\022B\n\014alternatives\030\001 \003(\0132,.speech_" +
      "to_text.SpeechRecognitionAlternative\022\023\n\013" +
      "channel_tag\030\002 \001(\005\"\263\001\n\032StreamingRecogniti" +
      "onResult\022B\n\014alternatives\030\001 \003(\0132,.speech_" +
      "to_text.SpeechRecognitionAlternative\022\020\n\010" +
      "is_final\030\002 \001(\010\022\021\n\tstability\030\003 \001(\002\022\027\n\017res" +
      "ult_end_time\030\004 \001(\002\022\023\n\013channel_tag\030\005 \001(\005\"" +
      "o\n\034SpeechRecognitionAlternative\022\022\n\ntrans" +
      "cript\030\001 \001(\t\022\022\n\nconfidence\030\002 \001(\002\022\'\n\005words" +
      "\030\003 \003(\0132\030.speech_to_text.WordInfo\">\n\010Word" +
      "Info\022\022\n\nstart_time\030\001 \001(\002\022\020\n\010end_time\030\002 \001" +
      "(\002\022\014\n\004word\030\003 \001(\t\"\236\001\n\017SpeechOperation\022\014\n\004" +
      "name\030\001 \001(\t\022\014\n\004done\030\002 \001(\010\022#\n\005error\030\003 \001(\0132" +
      "\022.google.rpc.StatusH\000\022@\n\010response\030\004 \001(\0132" +
      ",.speech_to_text.LongRunningRecognizeRes" +
      "ponseH\000B\010\n\006result2\362\003\n\014SpeechToText\022\200\001\n\tR" +
      "ecognize\022 .speech_to_text.RecognizeReque" +
      "st\032!.speech_to_text.RecognizeResponse\".\202" +
      "\323\344\223\002\031\"\024/v1/speech:recognize:\001*\332A\014config," +
      "audio\022q\n\022StreamingRecognize\022).speech_to_" +
      "text.StreamingRecognizeRequest\032*.speech_" +
      "to_text.StreamingRecognizeResponse\"\000(\0010\001" +
      "\022f\n\024LongRunningRecognize\022+.speech_to_tex" +
      "t.LongRunningRecognizeRequest\032\037.speech_t" +
      "o_text.SpeechOperation\"\000\022\203\001\n\022GetSpeechOp" +
      "eration\022&.speech_to_text.SpeechOperation" +
      "Request\032\037.speech_to_text.SpeechOperation" +
      "\"$\202\323\344\223\002\036\022\034/v1/speech_operations/{name}B+" +
      "\n\024ai.vernacular.speechB\021SpeechToTextProt" +
      "oP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          com.google.api.ClientProto.getDescriptor(),
          com.google.api.FieldBehaviorProto.getDescriptor(),
          com.google.rpc.StatusProto.getDescriptor(),
        });
    internal_static_speech_to_text_RecognizeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_speech_to_text_RecognizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_RecognizeRequest_descriptor,
        new java.lang.String[] { "Config", "Audio", "Segment", });
    internal_static_speech_to_text_LongRunningRecognizeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_speech_to_text_LongRunningRecognizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_LongRunningRecognizeRequest_descriptor,
        new java.lang.String[] { "Config", "Audio", "ResultUrl", "Segment", });
    internal_static_speech_to_text_SpeechOperationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_speech_to_text_SpeechOperationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_SpeechOperationRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_speech_to_text_StreamingRecognizeRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_speech_to_text_StreamingRecognizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_StreamingRecognizeRequest_descriptor,
        new java.lang.String[] { "StreamingConfig", "AudioContent", "StreamingRequest", });
    internal_static_speech_to_text_StreamingRecognitionConfig_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_speech_to_text_StreamingRecognitionConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_StreamingRecognitionConfig_descriptor,
        new java.lang.String[] { "Config", "InterimResults", });
    internal_static_speech_to_text_RecognitionConfig_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_speech_to_text_RecognitionConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_RecognitionConfig_descriptor,
        new java.lang.String[] { "Encoding", "SampleRateHertz", "LanguageCode", "MaxAlternatives", "SpeechContexts", "AudioChannelCount", "EnableSeparateRecognitionPerChannel", "EnableWordTimeOffsets", "EnableAutomaticPunctuation", "DiarizationConfig", });
    internal_static_speech_to_text_SpeechContext_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_speech_to_text_SpeechContext_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_SpeechContext_descriptor,
        new java.lang.String[] { "Phrases", });
    internal_static_speech_to_text_SpeakerDiarizationConfig_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_speech_to_text_SpeakerDiarizationConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_SpeakerDiarizationConfig_descriptor,
        new java.lang.String[] { "EnableSpeakerDiarization", "MinSpeakerCount", "MaxSpeakerCount", });
    internal_static_speech_to_text_RecognitionAudio_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_speech_to_text_RecognitionAudio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_RecognitionAudio_descriptor,
        new java.lang.String[] { "Content", "Uri", "AudioSource", });
    internal_static_speech_to_text_RecognizeResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_speech_to_text_RecognizeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_RecognizeResponse_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_speech_to_text_LongRunningRecognizeResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_speech_to_text_LongRunningRecognizeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_LongRunningRecognizeResponse_descriptor,
        new java.lang.String[] { "Results", });
    internal_static_speech_to_text_StreamingRecognizeResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_speech_to_text_StreamingRecognizeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_StreamingRecognizeResponse_descriptor,
        new java.lang.String[] { "Error", "Results", });
    internal_static_speech_to_text_SpeechRecognitionResult_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_speech_to_text_SpeechRecognitionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_SpeechRecognitionResult_descriptor,
        new java.lang.String[] { "Alternatives", "ChannelTag", });
    internal_static_speech_to_text_StreamingRecognitionResult_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_speech_to_text_StreamingRecognitionResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_StreamingRecognitionResult_descriptor,
        new java.lang.String[] { "Alternatives", "IsFinal", "Stability", "ResultEndTime", "ChannelTag", });
    internal_static_speech_to_text_SpeechRecognitionAlternative_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_speech_to_text_SpeechRecognitionAlternative_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_SpeechRecognitionAlternative_descriptor,
        new java.lang.String[] { "Transcript", "Confidence", "Words", });
    internal_static_speech_to_text_WordInfo_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_speech_to_text_WordInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_WordInfo_descriptor,
        new java.lang.String[] { "StartTime", "EndTime", "Word", });
    internal_static_speech_to_text_SpeechOperation_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_speech_to_text_SpeechOperation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_speech_to_text_SpeechOperation_descriptor,
        new java.lang.String[] { "Name", "Done", "Error", "Response", "Result", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
