// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

/**
 * Protobuf type {@code speech_to_text.SpeechRecognitionResult}
 */
public  final class SpeechRecognitionResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:speech_to_text.SpeechRecognitionResult)
    SpeechRecognitionResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpeechRecognitionResult.newBuilder() to construct.
  private SpeechRecognitionResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpeechRecognitionResult() {
    alternatives_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SpeechRecognitionResult();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpeechRecognitionResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              alternatives_ = new java.util.ArrayList<ai.vernacular.speech.SpeechRecognitionAlternative>();
              mutable_bitField0_ |= 0x00000001;
            }
            alternatives_.add(
                input.readMessage(ai.vernacular.speech.SpeechRecognitionAlternative.parser(), extensionRegistry));
            break;
          }
          case 16: {

            channelTag_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        alternatives_ = java.util.Collections.unmodifiableList(alternatives_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_SpeechRecognitionResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_SpeechRecognitionResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.vernacular.speech.SpeechRecognitionResult.class, ai.vernacular.speech.SpeechRecognitionResult.Builder.class);
  }

  public static final int ALTERNATIVES_FIELD_NUMBER = 1;
  private java.util.List<ai.vernacular.speech.SpeechRecognitionAlternative> alternatives_;
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  public java.util.List<ai.vernacular.speech.SpeechRecognitionAlternative> getAlternativesList() {
    return alternatives_;
  }
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  public java.util.List<? extends ai.vernacular.speech.SpeechRecognitionAlternativeOrBuilder> 
      getAlternativesOrBuilderList() {
    return alternatives_;
  }
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  public int getAlternativesCount() {
    return alternatives_.size();
  }
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  public ai.vernacular.speech.SpeechRecognitionAlternative getAlternatives(int index) {
    return alternatives_.get(index);
  }
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  public ai.vernacular.speech.SpeechRecognitionAlternativeOrBuilder getAlternativesOrBuilder(
      int index) {
    return alternatives_.get(index);
  }

  public static final int CHANNEL_TAG_FIELD_NUMBER = 2;
  private int channelTag_;
  /**
   * <code>int32 channel_tag = 2;</code>
   * @return The channelTag.
   */
  public int getChannelTag() {
    return channelTag_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < alternatives_.size(); i++) {
      output.writeMessage(1, alternatives_.get(i));
    }
    if (channelTag_ != 0) {
      output.writeInt32(2, channelTag_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < alternatives_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, alternatives_.get(i));
    }
    if (channelTag_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, channelTag_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.vernacular.speech.SpeechRecognitionResult)) {
      return super.equals(obj);
    }
    ai.vernacular.speech.SpeechRecognitionResult other = (ai.vernacular.speech.SpeechRecognitionResult) obj;

    if (!getAlternativesList()
        .equals(other.getAlternativesList())) return false;
    if (getChannelTag()
        != other.getChannelTag()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getAlternativesCount() > 0) {
      hash = (37 * hash) + ALTERNATIVES_FIELD_NUMBER;
      hash = (53 * hash) + getAlternativesList().hashCode();
    }
    hash = (37 * hash) + CHANNEL_TAG_FIELD_NUMBER;
    hash = (53 * hash) + getChannelTag();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.vernacular.speech.SpeechRecognitionResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.SpeechRecognitionResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.vernacular.speech.SpeechRecognitionResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code speech_to_text.SpeechRecognitionResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:speech_to_text.SpeechRecognitionResult)
      ai.vernacular.speech.SpeechRecognitionResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_SpeechRecognitionResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_SpeechRecognitionResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.vernacular.speech.SpeechRecognitionResult.class, ai.vernacular.speech.SpeechRecognitionResult.Builder.class);
    }

    // Construct using ai.vernacular.speech.SpeechRecognitionResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getAlternativesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (alternativesBuilder_ == null) {
        alternatives_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        alternativesBuilder_.clear();
      }
      channelTag_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_SpeechRecognitionResult_descriptor;
    }

    @java.lang.Override
    public ai.vernacular.speech.SpeechRecognitionResult getDefaultInstanceForType() {
      return ai.vernacular.speech.SpeechRecognitionResult.getDefaultInstance();
    }

    @java.lang.Override
    public ai.vernacular.speech.SpeechRecognitionResult build() {
      ai.vernacular.speech.SpeechRecognitionResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.vernacular.speech.SpeechRecognitionResult buildPartial() {
      ai.vernacular.speech.SpeechRecognitionResult result = new ai.vernacular.speech.SpeechRecognitionResult(this);
      int from_bitField0_ = bitField0_;
      if (alternativesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          alternatives_ = java.util.Collections.unmodifiableList(alternatives_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.alternatives_ = alternatives_;
      } else {
        result.alternatives_ = alternativesBuilder_.build();
      }
      result.channelTag_ = channelTag_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.vernacular.speech.SpeechRecognitionResult) {
        return mergeFrom((ai.vernacular.speech.SpeechRecognitionResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.vernacular.speech.SpeechRecognitionResult other) {
      if (other == ai.vernacular.speech.SpeechRecognitionResult.getDefaultInstance()) return this;
      if (alternativesBuilder_ == null) {
        if (!other.alternatives_.isEmpty()) {
          if (alternatives_.isEmpty()) {
            alternatives_ = other.alternatives_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAlternativesIsMutable();
            alternatives_.addAll(other.alternatives_);
          }
          onChanged();
        }
      } else {
        if (!other.alternatives_.isEmpty()) {
          if (alternativesBuilder_.isEmpty()) {
            alternativesBuilder_.dispose();
            alternativesBuilder_ = null;
            alternatives_ = other.alternatives_;
            bitField0_ = (bitField0_ & ~0x00000001);
            alternativesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAlternativesFieldBuilder() : null;
          } else {
            alternativesBuilder_.addAllMessages(other.alternatives_);
          }
        }
      }
      if (other.getChannelTag() != 0) {
        setChannelTag(other.getChannelTag());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.vernacular.speech.SpeechRecognitionResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.vernacular.speech.SpeechRecognitionResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<ai.vernacular.speech.SpeechRecognitionAlternative> alternatives_ =
      java.util.Collections.emptyList();
    private void ensureAlternativesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        alternatives_ = new java.util.ArrayList<ai.vernacular.speech.SpeechRecognitionAlternative>(alternatives_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        ai.vernacular.speech.SpeechRecognitionAlternative, ai.vernacular.speech.SpeechRecognitionAlternative.Builder, ai.vernacular.speech.SpeechRecognitionAlternativeOrBuilder> alternativesBuilder_;

    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public java.util.List<ai.vernacular.speech.SpeechRecognitionAlternative> getAlternativesList() {
      if (alternativesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(alternatives_);
      } else {
        return alternativesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public int getAlternativesCount() {
      if (alternativesBuilder_ == null) {
        return alternatives_.size();
      } else {
        return alternativesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public ai.vernacular.speech.SpeechRecognitionAlternative getAlternatives(int index) {
      if (alternativesBuilder_ == null) {
        return alternatives_.get(index);
      } else {
        return alternativesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder setAlternatives(
        int index, ai.vernacular.speech.SpeechRecognitionAlternative value) {
      if (alternativesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternativesIsMutable();
        alternatives_.set(index, value);
        onChanged();
      } else {
        alternativesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder setAlternatives(
        int index, ai.vernacular.speech.SpeechRecognitionAlternative.Builder builderForValue) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.set(index, builderForValue.build());
        onChanged();
      } else {
        alternativesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder addAlternatives(ai.vernacular.speech.SpeechRecognitionAlternative value) {
      if (alternativesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternativesIsMutable();
        alternatives_.add(value);
        onChanged();
      } else {
        alternativesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder addAlternatives(
        int index, ai.vernacular.speech.SpeechRecognitionAlternative value) {
      if (alternativesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAlternativesIsMutable();
        alternatives_.add(index, value);
        onChanged();
      } else {
        alternativesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder addAlternatives(
        ai.vernacular.speech.SpeechRecognitionAlternative.Builder builderForValue) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.add(builderForValue.build());
        onChanged();
      } else {
        alternativesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder addAlternatives(
        int index, ai.vernacular.speech.SpeechRecognitionAlternative.Builder builderForValue) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.add(index, builderForValue.build());
        onChanged();
      } else {
        alternativesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder addAllAlternatives(
        java.lang.Iterable<? extends ai.vernacular.speech.SpeechRecognitionAlternative> values) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, alternatives_);
        onChanged();
      } else {
        alternativesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder clearAlternatives() {
      if (alternativesBuilder_ == null) {
        alternatives_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        alternativesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public Builder removeAlternatives(int index) {
      if (alternativesBuilder_ == null) {
        ensureAlternativesIsMutable();
        alternatives_.remove(index);
        onChanged();
      } else {
        alternativesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public ai.vernacular.speech.SpeechRecognitionAlternative.Builder getAlternativesBuilder(
        int index) {
      return getAlternativesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public ai.vernacular.speech.SpeechRecognitionAlternativeOrBuilder getAlternativesOrBuilder(
        int index) {
      if (alternativesBuilder_ == null) {
        return alternatives_.get(index);  } else {
        return alternativesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public java.util.List<? extends ai.vernacular.speech.SpeechRecognitionAlternativeOrBuilder> 
         getAlternativesOrBuilderList() {
      if (alternativesBuilder_ != null) {
        return alternativesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(alternatives_);
      }
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public ai.vernacular.speech.SpeechRecognitionAlternative.Builder addAlternativesBuilder() {
      return getAlternativesFieldBuilder().addBuilder(
          ai.vernacular.speech.SpeechRecognitionAlternative.getDefaultInstance());
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public ai.vernacular.speech.SpeechRecognitionAlternative.Builder addAlternativesBuilder(
        int index) {
      return getAlternativesFieldBuilder().addBuilder(
          index, ai.vernacular.speech.SpeechRecognitionAlternative.getDefaultInstance());
    }
    /**
     * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
     */
    public java.util.List<ai.vernacular.speech.SpeechRecognitionAlternative.Builder> 
         getAlternativesBuilderList() {
      return getAlternativesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        ai.vernacular.speech.SpeechRecognitionAlternative, ai.vernacular.speech.SpeechRecognitionAlternative.Builder, ai.vernacular.speech.SpeechRecognitionAlternativeOrBuilder> 
        getAlternativesFieldBuilder() {
      if (alternativesBuilder_ == null) {
        alternativesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            ai.vernacular.speech.SpeechRecognitionAlternative, ai.vernacular.speech.SpeechRecognitionAlternative.Builder, ai.vernacular.speech.SpeechRecognitionAlternativeOrBuilder>(
                alternatives_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        alternatives_ = null;
      }
      return alternativesBuilder_;
    }

    private int channelTag_ ;
    /**
     * <code>int32 channel_tag = 2;</code>
     * @return The channelTag.
     */
    public int getChannelTag() {
      return channelTag_;
    }
    /**
     * <code>int32 channel_tag = 2;</code>
     * @param value The channelTag to set.
     * @return This builder for chaining.
     */
    public Builder setChannelTag(int value) {
      
      channelTag_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 channel_tag = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearChannelTag() {
      
      channelTag_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:speech_to_text.SpeechRecognitionResult)
  }

  // @@protoc_insertion_point(class_scope:speech_to_text.SpeechRecognitionResult)
  private static final ai.vernacular.speech.SpeechRecognitionResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.vernacular.speech.SpeechRecognitionResult();
  }

  public static ai.vernacular.speech.SpeechRecognitionResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpeechRecognitionResult>
      PARSER = new com.google.protobuf.AbstractParser<SpeechRecognitionResult>() {
    @java.lang.Override
    public SpeechRecognitionResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpeechRecognitionResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpeechRecognitionResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SpeechRecognitionResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.vernacular.speech.SpeechRecognitionResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

