// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

public interface SpeechRecognitionAlternativeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech_to_text.SpeechRecognitionAlternative)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transcript = 1;</code>
   * @return The transcript.
   */
  java.lang.String getTranscript();
  /**
   * <code>string transcript = 1;</code>
   * @return The bytes for transcript.
   */
  com.google.protobuf.ByteString
      getTranscriptBytes();

  /**
   * <code>float confidence = 2;</code>
   * @return The confidence.
   */
  float getConfidence();

  /**
   * <code>repeated .speech_to_text.WordInfo words = 3;</code>
   */
  java.util.List<ai.vernacular.speech.WordInfo> 
      getWordsList();
  /**
   * <code>repeated .speech_to_text.WordInfo words = 3;</code>
   */
  ai.vernacular.speech.WordInfo getWords(int index);
  /**
   * <code>repeated .speech_to_text.WordInfo words = 3;</code>
   */
  int getWordsCount();
  /**
   * <code>repeated .speech_to_text.WordInfo words = 3;</code>
   */
  java.util.List<? extends ai.vernacular.speech.WordInfoOrBuilder> 
      getWordsOrBuilderList();
  /**
   * <code>repeated .speech_to_text.WordInfo words = 3;</code>
   */
  ai.vernacular.speech.WordInfoOrBuilder getWordsOrBuilder(
      int index);
}
