// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

/**
 * Protobuf type {@code speech_to_text.LongRunningRecognizeRequest}
 */
public  final class LongRunningRecognizeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:speech_to_text.LongRunningRecognizeRequest)
    LongRunningRecognizeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LongRunningRecognizeRequest.newBuilder() to construct.
  private LongRunningRecognizeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LongRunningRecognizeRequest() {
    resultUrl_ = "";
    segment_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LongRunningRecognizeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LongRunningRecognizeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ai.vernacular.speech.RecognitionConfig.Builder subBuilder = null;
            if (config_ != null) {
              subBuilder = config_.toBuilder();
            }
            config_ = input.readMessage(ai.vernacular.speech.RecognitionConfig.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(config_);
              config_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            ai.vernacular.speech.RecognitionAudio.Builder subBuilder = null;
            if (audio_ != null) {
              subBuilder = audio_.toBuilder();
            }
            audio_ = input.readMessage(ai.vernacular.speech.RecognitionAudio.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(audio_);
              audio_ = subBuilder.buildPartial();
            }

            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            resultUrl_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            segment_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_LongRunningRecognizeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_LongRunningRecognizeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.vernacular.speech.LongRunningRecognizeRequest.class, ai.vernacular.speech.LongRunningRecognizeRequest.Builder.class);
  }

  public static final int CONFIG_FIELD_NUMBER = 1;
  private ai.vernacular.speech.RecognitionConfig config_;
  /**
   * <pre>
   * Required. Provides information to the recognizer that specifies how to
   * process the request.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the config field is set.
   */
  public boolean hasConfig() {
    return config_ != null;
  }
  /**
   * <pre>
   * Required. Provides information to the recognizer that specifies how to
   * process the request.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The config.
   */
  public ai.vernacular.speech.RecognitionConfig getConfig() {
    return config_ == null ? ai.vernacular.speech.RecognitionConfig.getDefaultInstance() : config_;
  }
  /**
   * <pre>
   * Required. Provides information to the recognizer that specifies how to
   * process the request.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  public ai.vernacular.speech.RecognitionConfigOrBuilder getConfigOrBuilder() {
    return getConfig();
  }

  public static final int AUDIO_FIELD_NUMBER = 2;
  private ai.vernacular.speech.RecognitionAudio audio_;
  /**
   * <pre>
   * Required. The audio data to be recognized.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the audio field is set.
   */
  public boolean hasAudio() {
    return audio_ != null;
  }
  /**
   * <pre>
   * Required. The audio data to be recognized.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The audio.
   */
  public ai.vernacular.speech.RecognitionAudio getAudio() {
    return audio_ == null ? ai.vernacular.speech.RecognitionAudio.getDefaultInstance() : audio_;
  }
  /**
   * <pre>
   * Required. The audio data to be recognized.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  public ai.vernacular.speech.RecognitionAudioOrBuilder getAudioOrBuilder() {
    return getAudio();
  }

  public static final int RESULT_URL_FIELD_NUMBER = 11;
  private volatile java.lang.Object resultUrl_;
  /**
   * <pre>
   * Optional. When operation completes, result is posted to this url if provided.
   * </pre>
   *
   * <code>string result_url = 11;</code>
   * @return The resultUrl.
   */
  public java.lang.String getResultUrl() {
    java.lang.Object ref = resultUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resultUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Optional. When operation completes, result is posted to this url if provided.
   * </pre>
   *
   * <code>string result_url = 11;</code>
   * @return The bytes for resultUrl.
   */
  public com.google.protobuf.ByteString
      getResultUrlBytes() {
    java.lang.Object ref = resultUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resultUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEGMENT_FIELD_NUMBER = 16;
  private volatile java.lang.Object segment_;
  /**
   * <code>string segment = 16;</code>
   * @return The segment.
   */
  public java.lang.String getSegment() {
    java.lang.Object ref = segment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      segment_ = s;
      return s;
    }
  }
  /**
   * <code>string segment = 16;</code>
   * @return The bytes for segment.
   */
  public com.google.protobuf.ByteString
      getSegmentBytes() {
    java.lang.Object ref = segment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      segment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (config_ != null) {
      output.writeMessage(1, getConfig());
    }
    if (audio_ != null) {
      output.writeMessage(2, getAudio());
    }
    if (!getResultUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, resultUrl_);
    }
    if (!getSegmentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, segment_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (config_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getConfig());
    }
    if (audio_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAudio());
    }
    if (!getResultUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, resultUrl_);
    }
    if (!getSegmentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, segment_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.vernacular.speech.LongRunningRecognizeRequest)) {
      return super.equals(obj);
    }
    ai.vernacular.speech.LongRunningRecognizeRequest other = (ai.vernacular.speech.LongRunningRecognizeRequest) obj;

    if (hasConfig() != other.hasConfig()) return false;
    if (hasConfig()) {
      if (!getConfig()
          .equals(other.getConfig())) return false;
    }
    if (hasAudio() != other.hasAudio()) return false;
    if (hasAudio()) {
      if (!getAudio()
          .equals(other.getAudio())) return false;
    }
    if (!getResultUrl()
        .equals(other.getResultUrl())) return false;
    if (!getSegment()
        .equals(other.getSegment())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasConfig()) {
      hash = (37 * hash) + CONFIG_FIELD_NUMBER;
      hash = (53 * hash) + getConfig().hashCode();
    }
    if (hasAudio()) {
      hash = (37 * hash) + AUDIO_FIELD_NUMBER;
      hash = (53 * hash) + getAudio().hashCode();
    }
    hash = (37 * hash) + RESULT_URL_FIELD_NUMBER;
    hash = (53 * hash) + getResultUrl().hashCode();
    hash = (37 * hash) + SEGMENT_FIELD_NUMBER;
    hash = (53 * hash) + getSegment().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.vernacular.speech.LongRunningRecognizeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.LongRunningRecognizeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.vernacular.speech.LongRunningRecognizeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code speech_to_text.LongRunningRecognizeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:speech_to_text.LongRunningRecognizeRequest)
      ai.vernacular.speech.LongRunningRecognizeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_LongRunningRecognizeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_LongRunningRecognizeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.vernacular.speech.LongRunningRecognizeRequest.class, ai.vernacular.speech.LongRunningRecognizeRequest.Builder.class);
    }

    // Construct using ai.vernacular.speech.LongRunningRecognizeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (configBuilder_ == null) {
        config_ = null;
      } else {
        config_ = null;
        configBuilder_ = null;
      }
      if (audioBuilder_ == null) {
        audio_ = null;
      } else {
        audio_ = null;
        audioBuilder_ = null;
      }
      resultUrl_ = "";

      segment_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_LongRunningRecognizeRequest_descriptor;
    }

    @java.lang.Override
    public ai.vernacular.speech.LongRunningRecognizeRequest getDefaultInstanceForType() {
      return ai.vernacular.speech.LongRunningRecognizeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ai.vernacular.speech.LongRunningRecognizeRequest build() {
      ai.vernacular.speech.LongRunningRecognizeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.vernacular.speech.LongRunningRecognizeRequest buildPartial() {
      ai.vernacular.speech.LongRunningRecognizeRequest result = new ai.vernacular.speech.LongRunningRecognizeRequest(this);
      if (configBuilder_ == null) {
        result.config_ = config_;
      } else {
        result.config_ = configBuilder_.build();
      }
      if (audioBuilder_ == null) {
        result.audio_ = audio_;
      } else {
        result.audio_ = audioBuilder_.build();
      }
      result.resultUrl_ = resultUrl_;
      result.segment_ = segment_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.vernacular.speech.LongRunningRecognizeRequest) {
        return mergeFrom((ai.vernacular.speech.LongRunningRecognizeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.vernacular.speech.LongRunningRecognizeRequest other) {
      if (other == ai.vernacular.speech.LongRunningRecognizeRequest.getDefaultInstance()) return this;
      if (other.hasConfig()) {
        mergeConfig(other.getConfig());
      }
      if (other.hasAudio()) {
        mergeAudio(other.getAudio());
      }
      if (!other.getResultUrl().isEmpty()) {
        resultUrl_ = other.resultUrl_;
        onChanged();
      }
      if (!other.getSegment().isEmpty()) {
        segment_ = other.segment_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.vernacular.speech.LongRunningRecognizeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.vernacular.speech.LongRunningRecognizeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ai.vernacular.speech.RecognitionConfig config_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.vernacular.speech.RecognitionConfig, ai.vernacular.speech.RecognitionConfig.Builder, ai.vernacular.speech.RecognitionConfigOrBuilder> configBuilder_;
    /**
     * <pre>
     * Required. Provides information to the recognizer that specifies how to
     * process the request.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the config field is set.
     */
    public boolean hasConfig() {
      return configBuilder_ != null || config_ != null;
    }
    /**
     * <pre>
     * Required. Provides information to the recognizer that specifies how to
     * process the request.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The config.
     */
    public ai.vernacular.speech.RecognitionConfig getConfig() {
      if (configBuilder_ == null) {
        return config_ == null ? ai.vernacular.speech.RecognitionConfig.getDefaultInstance() : config_;
      } else {
        return configBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Required. Provides information to the recognizer that specifies how to
     * process the request.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setConfig(ai.vernacular.speech.RecognitionConfig value) {
      if (configBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        config_ = value;
        onChanged();
      } else {
        configBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. Provides information to the recognizer that specifies how to
     * process the request.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setConfig(
        ai.vernacular.speech.RecognitionConfig.Builder builderForValue) {
      if (configBuilder_ == null) {
        config_ = builderForValue.build();
        onChanged();
      } else {
        configBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Required. Provides information to the recognizer that specifies how to
     * process the request.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeConfig(ai.vernacular.speech.RecognitionConfig value) {
      if (configBuilder_ == null) {
        if (config_ != null) {
          config_ =
            ai.vernacular.speech.RecognitionConfig.newBuilder(config_).mergeFrom(value).buildPartial();
        } else {
          config_ = value;
        }
        onChanged();
      } else {
        configBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. Provides information to the recognizer that specifies how to
     * process the request.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearConfig() {
      if (configBuilder_ == null) {
        config_ = null;
        onChanged();
      } else {
        config_ = null;
        configBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Required. Provides information to the recognizer that specifies how to
     * process the request.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public ai.vernacular.speech.RecognitionConfig.Builder getConfigBuilder() {
      
      onChanged();
      return getConfigFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Required. Provides information to the recognizer that specifies how to
     * process the request.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public ai.vernacular.speech.RecognitionConfigOrBuilder getConfigOrBuilder() {
      if (configBuilder_ != null) {
        return configBuilder_.getMessageOrBuilder();
      } else {
        return config_ == null ?
            ai.vernacular.speech.RecognitionConfig.getDefaultInstance() : config_;
      }
    }
    /**
     * <pre>
     * Required. Provides information to the recognizer that specifies how to
     * process the request.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.vernacular.speech.RecognitionConfig, ai.vernacular.speech.RecognitionConfig.Builder, ai.vernacular.speech.RecognitionConfigOrBuilder> 
        getConfigFieldBuilder() {
      if (configBuilder_ == null) {
        configBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.vernacular.speech.RecognitionConfig, ai.vernacular.speech.RecognitionConfig.Builder, ai.vernacular.speech.RecognitionConfigOrBuilder>(
                getConfig(),
                getParentForChildren(),
                isClean());
        config_ = null;
      }
      return configBuilder_;
    }

    private ai.vernacular.speech.RecognitionAudio audio_;
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.vernacular.speech.RecognitionAudio, ai.vernacular.speech.RecognitionAudio.Builder, ai.vernacular.speech.RecognitionAudioOrBuilder> audioBuilder_;
    /**
     * <pre>
     * Required. The audio data to be recognized.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return Whether the audio field is set.
     */
    public boolean hasAudio() {
      return audioBuilder_ != null || audio_ != null;
    }
    /**
     * <pre>
     * Required. The audio data to be recognized.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     * @return The audio.
     */
    public ai.vernacular.speech.RecognitionAudio getAudio() {
      if (audioBuilder_ == null) {
        return audio_ == null ? ai.vernacular.speech.RecognitionAudio.getDefaultInstance() : audio_;
      } else {
        return audioBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Required. The audio data to be recognized.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setAudio(ai.vernacular.speech.RecognitionAudio value) {
      if (audioBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        audio_ = value;
        onChanged();
      } else {
        audioBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. The audio data to be recognized.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder setAudio(
        ai.vernacular.speech.RecognitionAudio.Builder builderForValue) {
      if (audioBuilder_ == null) {
        audio_ = builderForValue.build();
        onChanged();
      } else {
        audioBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * Required. The audio data to be recognized.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder mergeAudio(ai.vernacular.speech.RecognitionAudio value) {
      if (audioBuilder_ == null) {
        if (audio_ != null) {
          audio_ =
            ai.vernacular.speech.RecognitionAudio.newBuilder(audio_).mergeFrom(value).buildPartial();
        } else {
          audio_ = value;
        }
        onChanged();
      } else {
        audioBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * Required. The audio data to be recognized.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public Builder clearAudio() {
      if (audioBuilder_ == null) {
        audio_ = null;
        onChanged();
      } else {
        audio_ = null;
        audioBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * Required. The audio data to be recognized.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public ai.vernacular.speech.RecognitionAudio.Builder getAudioBuilder() {
      
      onChanged();
      return getAudioFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Required. The audio data to be recognized.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    public ai.vernacular.speech.RecognitionAudioOrBuilder getAudioOrBuilder() {
      if (audioBuilder_ != null) {
        return audioBuilder_.getMessageOrBuilder();
      } else {
        return audio_ == null ?
            ai.vernacular.speech.RecognitionAudio.getDefaultInstance() : audio_;
      }
    }
    /**
     * <pre>
     * Required. The audio data to be recognized.
     * </pre>
     *
     * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ai.vernacular.speech.RecognitionAudio, ai.vernacular.speech.RecognitionAudio.Builder, ai.vernacular.speech.RecognitionAudioOrBuilder> 
        getAudioFieldBuilder() {
      if (audioBuilder_ == null) {
        audioBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ai.vernacular.speech.RecognitionAudio, ai.vernacular.speech.RecognitionAudio.Builder, ai.vernacular.speech.RecognitionAudioOrBuilder>(
                getAudio(),
                getParentForChildren(),
                isClean());
        audio_ = null;
      }
      return audioBuilder_;
    }

    private java.lang.Object resultUrl_ = "";
    /**
     * <pre>
     * Optional. When operation completes, result is posted to this url if provided.
     * </pre>
     *
     * <code>string result_url = 11;</code>
     * @return The resultUrl.
     */
    public java.lang.String getResultUrl() {
      java.lang.Object ref = resultUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Optional. When operation completes, result is posted to this url if provided.
     * </pre>
     *
     * <code>string result_url = 11;</code>
     * @return The bytes for resultUrl.
     */
    public com.google.protobuf.ByteString
        getResultUrlBytes() {
      java.lang.Object ref = resultUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Optional. When operation completes, result is posted to this url if provided.
     * </pre>
     *
     * <code>string result_url = 11;</code>
     * @param value The resultUrl to set.
     * @return This builder for chaining.
     */
    public Builder setResultUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resultUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. When operation completes, result is posted to this url if provided.
     * </pre>
     *
     * <code>string result_url = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultUrl() {
      
      resultUrl_ = getDefaultInstance().getResultUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional. When operation completes, result is posted to this url if provided.
     * </pre>
     *
     * <code>string result_url = 11;</code>
     * @param value The bytes for resultUrl to set.
     * @return This builder for chaining.
     */
    public Builder setResultUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resultUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object segment_ = "";
    /**
     * <code>string segment = 16;</code>
     * @return The segment.
     */
    public java.lang.String getSegment() {
      java.lang.Object ref = segment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        segment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string segment = 16;</code>
     * @return The bytes for segment.
     */
    public com.google.protobuf.ByteString
        getSegmentBytes() {
      java.lang.Object ref = segment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        segment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string segment = 16;</code>
     * @param value The segment to set.
     * @return This builder for chaining.
     */
    public Builder setSegment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      segment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string segment = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearSegment() {
      
      segment_ = getDefaultInstance().getSegment();
      onChanged();
      return this;
    }
    /**
     * <code>string segment = 16;</code>
     * @param value The bytes for segment to set.
     * @return This builder for chaining.
     */
    public Builder setSegmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      segment_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:speech_to_text.LongRunningRecognizeRequest)
  }

  // @@protoc_insertion_point(class_scope:speech_to_text.LongRunningRecognizeRequest)
  private static final ai.vernacular.speech.LongRunningRecognizeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.vernacular.speech.LongRunningRecognizeRequest();
  }

  public static ai.vernacular.speech.LongRunningRecognizeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LongRunningRecognizeRequest>
      PARSER = new com.google.protobuf.AbstractParser<LongRunningRecognizeRequest>() {
    @java.lang.Override
    public LongRunningRecognizeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LongRunningRecognizeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LongRunningRecognizeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LongRunningRecognizeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.vernacular.speech.LongRunningRecognizeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

