// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

public interface LongRunningRecognizeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech_to_text.LongRunningRecognizeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Required. Provides information to the recognizer that specifies how to
   * process the request.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <pre>
   * Required. Provides information to the recognizer that specifies how to
   * process the request.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The config.
   */
  ai.vernacular.speech.RecognitionConfig getConfig();
  /**
   * <pre>
   * Required. Provides information to the recognizer that specifies how to
   * process the request.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionConfig config = 1 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  ai.vernacular.speech.RecognitionConfigOrBuilder getConfigOrBuilder();

  /**
   * <pre>
   * Required. The audio data to be recognized.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return Whether the audio field is set.
   */
  boolean hasAudio();
  /**
   * <pre>
   * Required. The audio data to be recognized.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   * @return The audio.
   */
  ai.vernacular.speech.RecognitionAudio getAudio();
  /**
   * <pre>
   * Required. The audio data to be recognized.
   * </pre>
   *
   * <code>.speech_to_text.RecognitionAudio audio = 2 [(.google.api.field_behavior) = REQUIRED];</code>
   */
  ai.vernacular.speech.RecognitionAudioOrBuilder getAudioOrBuilder();

  /**
   * <pre>
   * Optional. When operation completes, result is posted to this url if provided.
   * </pre>
   *
   * <code>string result_url = 11;</code>
   * @return The resultUrl.
   */
  java.lang.String getResultUrl();
  /**
   * <pre>
   * Optional. When operation completes, result is posted to this url if provided.
   * </pre>
   *
   * <code>string result_url = 11;</code>
   * @return The bytes for resultUrl.
   */
  com.google.protobuf.ByteString
      getResultUrlBytes();

  /**
   * <code>string segment = 16;</code>
   * @return The segment.
   */
  java.lang.String getSegment();
  /**
   * <code>string segment = 16;</code>
   * @return The bytes for segment.
   */
  com.google.protobuf.ByteString
      getSegmentBytes();
}
