// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

public interface SpeechRecognitionResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech_to_text.SpeechRecognitionResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  java.util.List<ai.vernacular.speech.SpeechRecognitionAlternative> 
      getAlternativesList();
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  ai.vernacular.speech.SpeechRecognitionAlternative getAlternatives(int index);
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  int getAlternativesCount();
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  java.util.List<? extends ai.vernacular.speech.SpeechRecognitionAlternativeOrBuilder> 
      getAlternativesOrBuilderList();
  /**
   * <code>repeated .speech_to_text.SpeechRecognitionAlternative alternatives = 1;</code>
   */
  ai.vernacular.speech.SpeechRecognitionAlternativeOrBuilder getAlternativesOrBuilder(
      int index);

  /**
   * <code>int32 channel_tag = 2;</code>
   * @return The channelTag.
   */
  int getChannelTag();
}
