// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

public interface SpeechContextOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech_to_text.SpeechContext)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string phrases = 1;</code>
   * @return A list containing the phrases.
   */
  java.util.List<java.lang.String>
      getPhrasesList();
  /**
   * <code>repeated string phrases = 1;</code>
   * @return The count of phrases.
   */
  int getPhrasesCount();
  /**
   * <code>repeated string phrases = 1;</code>
   * @param index The index of the element to return.
   * @return The phrases at the given index.
   */
  java.lang.String getPhrases(int index);
  /**
   * <code>repeated string phrases = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the phrases at the given index.
   */
  com.google.protobuf.ByteString
      getPhrasesBytes(int index);
}
