// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

public interface SpeechOperationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech_to_text.SpeechOperation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>bool done = 2;</code>
   * @return The done.
   */
  boolean getDone();

  /**
   * <pre>
   * If set, returns a [google.rpc.Status][google.rpc.Status] message that
   * specifies the error for the operation.
   * </pre>
   *
   * <code>.google.rpc.Status error = 3;</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <pre>
   * If set, returns a [google.rpc.Status][google.rpc.Status] message that
   * specifies the error for the operation.
   * </pre>
   *
   * <code>.google.rpc.Status error = 3;</code>
   * @return The error.
   */
  com.google.rpc.Status getError();
  /**
   * <pre>
   * If set, returns a [google.rpc.Status][google.rpc.Status] message that
   * specifies the error for the operation.
   * </pre>
   *
   * <code>.google.rpc.Status error = 3;</code>
   */
  com.google.rpc.StatusOrBuilder getErrorOrBuilder();

  /**
   * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
   * @return Whether the response field is set.
   */
  boolean hasResponse();
  /**
   * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
   * @return The response.
   */
  ai.vernacular.speech.LongRunningRecognizeResponse getResponse();
  /**
   * <code>.speech_to_text.LongRunningRecognizeResponse response = 4;</code>
   */
  ai.vernacular.speech.LongRunningRecognizeResponseOrBuilder getResponseOrBuilder();

  public ai.vernacular.speech.SpeechOperation.ResultCase getResultCase();
}
