// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

/**
 * Protobuf type {@code speech_to_text.WordInfo}
 */
public  final class WordInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:speech_to_text.WordInfo)
    WordInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WordInfo.newBuilder() to construct.
  private WordInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WordInfo() {
    word_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WordInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WordInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            startTime_ = input.readFloat();
            break;
          }
          case 21: {

            endTime_ = input.readFloat();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            word_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_WordInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_WordInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ai.vernacular.speech.WordInfo.class, ai.vernacular.speech.WordInfo.Builder.class);
  }

  public static final int START_TIME_FIELD_NUMBER = 1;
  private float startTime_;
  /**
   * <code>float start_time = 1;</code>
   * @return The startTime.
   */
  public float getStartTime() {
    return startTime_;
  }

  public static final int END_TIME_FIELD_NUMBER = 2;
  private float endTime_;
  /**
   * <code>float end_time = 2;</code>
   * @return The endTime.
   */
  public float getEndTime() {
    return endTime_;
  }

  public static final int WORD_FIELD_NUMBER = 3;
  private volatile java.lang.Object word_;
  /**
   * <code>string word = 3;</code>
   * @return The word.
   */
  public java.lang.String getWord() {
    java.lang.Object ref = word_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      word_ = s;
      return s;
    }
  }
  /**
   * <code>string word = 3;</code>
   * @return The bytes for word.
   */
  public com.google.protobuf.ByteString
      getWordBytes() {
    java.lang.Object ref = word_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      word_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (startTime_ != 0F) {
      output.writeFloat(1, startTime_);
    }
    if (endTime_ != 0F) {
      output.writeFloat(2, endTime_);
    }
    if (!getWordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, word_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (startTime_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, startTime_);
    }
    if (endTime_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, endTime_);
    }
    if (!getWordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, word_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ai.vernacular.speech.WordInfo)) {
      return super.equals(obj);
    }
    ai.vernacular.speech.WordInfo other = (ai.vernacular.speech.WordInfo) obj;

    if (java.lang.Float.floatToIntBits(getStartTime())
        != java.lang.Float.floatToIntBits(
            other.getStartTime())) return false;
    if (java.lang.Float.floatToIntBits(getEndTime())
        != java.lang.Float.floatToIntBits(
            other.getEndTime())) return false;
    if (!getWord()
        .equals(other.getWord())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + START_TIME_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getStartTime());
    hash = (37 * hash) + END_TIME_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getEndTime());
    hash = (37 * hash) + WORD_FIELD_NUMBER;
    hash = (53 * hash) + getWord().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ai.vernacular.speech.WordInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.WordInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.WordInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.WordInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.WordInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ai.vernacular.speech.WordInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ai.vernacular.speech.WordInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.WordInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.vernacular.speech.WordInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.WordInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ai.vernacular.speech.WordInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ai.vernacular.speech.WordInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ai.vernacular.speech.WordInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code speech_to_text.WordInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:speech_to_text.WordInfo)
      ai.vernacular.speech.WordInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_WordInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_WordInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ai.vernacular.speech.WordInfo.class, ai.vernacular.speech.WordInfo.Builder.class);
    }

    // Construct using ai.vernacular.speech.WordInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      startTime_ = 0F;

      endTime_ = 0F;

      word_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ai.vernacular.speech.SpeechToTextProto.internal_static_speech_to_text_WordInfo_descriptor;
    }

    @java.lang.Override
    public ai.vernacular.speech.WordInfo getDefaultInstanceForType() {
      return ai.vernacular.speech.WordInfo.getDefaultInstance();
    }

    @java.lang.Override
    public ai.vernacular.speech.WordInfo build() {
      ai.vernacular.speech.WordInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ai.vernacular.speech.WordInfo buildPartial() {
      ai.vernacular.speech.WordInfo result = new ai.vernacular.speech.WordInfo(this);
      result.startTime_ = startTime_;
      result.endTime_ = endTime_;
      result.word_ = word_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ai.vernacular.speech.WordInfo) {
        return mergeFrom((ai.vernacular.speech.WordInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ai.vernacular.speech.WordInfo other) {
      if (other == ai.vernacular.speech.WordInfo.getDefaultInstance()) return this;
      if (other.getStartTime() != 0F) {
        setStartTime(other.getStartTime());
      }
      if (other.getEndTime() != 0F) {
        setEndTime(other.getEndTime());
      }
      if (!other.getWord().isEmpty()) {
        word_ = other.word_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ai.vernacular.speech.WordInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ai.vernacular.speech.WordInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float startTime_ ;
    /**
     * <code>float start_time = 1;</code>
     * @return The startTime.
     */
    public float getStartTime() {
      return startTime_;
    }
    /**
     * <code>float start_time = 1;</code>
     * @param value The startTime to set.
     * @return This builder for chaining.
     */
    public Builder setStartTime(float value) {
      
      startTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float start_time = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStartTime() {
      
      startTime_ = 0F;
      onChanged();
      return this;
    }

    private float endTime_ ;
    /**
     * <code>float end_time = 2;</code>
     * @return The endTime.
     */
    public float getEndTime() {
      return endTime_;
    }
    /**
     * <code>float end_time = 2;</code>
     * @param value The endTime to set.
     * @return This builder for chaining.
     */
    public Builder setEndTime(float value) {
      
      endTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float end_time = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearEndTime() {
      
      endTime_ = 0F;
      onChanged();
      return this;
    }

    private java.lang.Object word_ = "";
    /**
     * <code>string word = 3;</code>
     * @return The word.
     */
    public java.lang.String getWord() {
      java.lang.Object ref = word_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        word_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string word = 3;</code>
     * @return The bytes for word.
     */
    public com.google.protobuf.ByteString
        getWordBytes() {
      java.lang.Object ref = word_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        word_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string word = 3;</code>
     * @param value The word to set.
     * @return This builder for chaining.
     */
    public Builder setWord(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      word_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string word = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWord() {
      
      word_ = getDefaultInstance().getWord();
      onChanged();
      return this;
    }
    /**
     * <code>string word = 3;</code>
     * @param value The bytes for word to set.
     * @return This builder for chaining.
     */
    public Builder setWordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      word_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:speech_to_text.WordInfo)
  }

  // @@protoc_insertion_point(class_scope:speech_to_text.WordInfo)
  private static final ai.vernacular.speech.WordInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ai.vernacular.speech.WordInfo();
  }

  public static ai.vernacular.speech.WordInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WordInfo>
      PARSER = new com.google.protobuf.AbstractParser<WordInfo>() {
    @java.lang.Override
    public WordInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WordInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WordInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WordInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ai.vernacular.speech.WordInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

