// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: speech-to-text.proto

package ai.vernacular.speech;

public interface WordInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:speech_to_text.WordInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float start_time = 1;</code>
   * @return The startTime.
   */
  float getStartTime();

  /**
   * <code>float end_time = 2;</code>
   * @return The endTime.
   */
  float getEndTime();

  /**
   * <code>string word = 3;</code>
   * @return The word.
   */
  java.lang.String getWord();
  /**
   * <code>string word = 3;</code>
   * @return The bytes for word.
   */
  com.google.protobuf.ByteString
      getWordBytes();
}
